program BomixBI;

//Pulo do gato!
{$WEAKLINKRTTI ON}

uses
  Vcl.Forms,
  funcaosistema_unit in 'Funcao\funcaosistema_unit.pas' {Sys_FuncaoSistema},
  FuncaoRestricoesInformacoes_Unit in 'Funcao\FuncaoRestricoesInformacoes_Unit.pas' {Sys_FuncaoRestricoesInformacoes},
  padraobi_unit in 'Padrao\padraobi_unit.pas' {PadraoBI},
  padraobuscador_unit in 'Padrao\padraobuscador_unit.pas' {PadraoBuscador},
  padraobuscadorfiltro_unit in 'Padrao\padraobuscadorfiltro_unit.pas' {PadraoBuscadorFiltro},
  padraocadastro_unit in 'Padrao\padraocadastro_unit.pas' {PadraoCadastro},
  padraocadastromax_unit in 'Padrao\padraocadastromax_unit.pas' {PadraoCadastroMax},
  conexaodados_unit in 'Estrutura\conexaodados_unit.pas' {Sys_ModuloConexaoDados: TDataModule},
  Inicializacao_Unit in 'Estrutura\Inicializacao_Unit.pas' {Sys_Inicializacao},
  principal_unit in 'Estrutura\principal_unit.pas' {Sys_Principal},
  Sys_UsuarioBuscadorFuncionario_Unit in 'Estrutura\Sys_UsuarioBuscadorFuncionario_Unit.pas' {Sys_UsuarioBuscadorFuncionario},
  SysFormularioBuscador_Unit in 'Estrutura\SysFormularioBuscador_Unit.pas' {Sys_FormularioBuscador},
  SysFormularioBuscadorSistema_Unit in 'Estrutura\SysFormularioBuscadorSistema_Unit.pas' {Sys_FormularioBuscadorSistema},
  sysformulariocadastro_unit in 'Estrutura\sysformulariocadastro_unit.pas' {Sys_FormularioCadastro},
  SysFormularioEvento_Unit in 'Estrutura\SysFormularioEvento_Unit.pas' {Sys_FormularioEvento},
  SysSetorCadastro_Unit in 'Estrutura\SysSetorCadastro_Unit.pas' {Sys_SetorCadastro},
  SysSistemaCadastro_Unit in 'Estrutura\SysSistemaCadastro_Unit.pas' {Sys_SistemaCadastro},
  SysUsuarioAcesso_Unit in 'Estrutura\SysUsuarioAcesso_Unit.pas' {Sys_UsuarioAcesso},
  SysUsuarioAcessoMostrarUsuario_Unit in 'Estrutura\SysUsuarioAcessoMostrarUsuario_Unit.pas' {Sys_UsuarioAcessoMostrarUsuario},
  SysUsuarioBuscador_Unit in 'Estrutura\SysUsuarioBuscador_Unit.pas' {Sys_UsuarioBuscador},
  SysUsuarioBuscadorArmazemControle_Unit in 'Estrutura\SysUsuarioBuscadorArmazemControle_Unit.pas' {Sys_UsuarioBuscadorArmazemControle},
  sysusuariobuscadorgrupo_unit in 'Estrutura\sysusuariobuscadorgrupo_unit.pas' {Sys_UsuarioBuscadorGrupo},
  SysUsuarioBuscadorRestrincao_Unit in 'Estrutura\SysUsuarioBuscadorRestrincao_Unit.pas' {Sys_UsuarioBuscadorRestrincao},
  SysUsuarioCadastro_Unit in 'Estrutura\SysUsuarioCadastro_Unit.pas' {Sys_UsuarioCadastro},
  SysUsuarioGrupo_Unit in 'Estrutura\SysUsuarioGrupo_Unit.pas' {Sys_UsuarioGrupo},
  SysUsuarioGrupoBuscador_Unit in 'Estrutura\SysUsuarioGrupoBuscador_Unit.pas' {Sys_UsuarioGrupoBuscador},
  SysUsuarioGrupoBuscadorSetor_Unit in 'Estrutura\SysUsuarioGrupoBuscadorSetor_Unit.pas' {Sys_UsuarioGrupoBuscadorSetor},
  UsuarioTrocarSenha_Unit in 'Estrutura\UsuarioTrocarSenha_Unit.pas' {Sys_UsuarioTrocarSenha},
  BI_PedidoVenda_ItensSemVendas_Unit in 'Forms\Comercial\PedidoDeVenda\BI_PedidoVenda_ItensSemVendas_Unit.pas' {BI_PedidoVenda_ItensSemVendas},
  BI_PedidoVenda_Unit in 'Forms\Comercial\PedidoDeVenda\BI_PedidoVenda_Unit.pas' {BI_PedidoVenda},
  BI_PedidoVendaCarregamento_Unit in 'Forms\Comercial\PedidoDeVenda\BI_PedidoVendaCarregamento_Unit.pas' {BI_PedidoVendaCarregamento},
  BI_PedidoVendaCarregamentoCriarCarga_Unit in 'Forms\Comercial\PedidoDeVenda\BI_PedidoVendaCarregamentoCriarCarga_Unit.pas' {BI_PedidoVendaCarregamentoCriar},
  BI_PedidoVendaCarregamentoModificarSaldo_Unit in 'Forms\Comercial\PedidoDeVenda\BI_PedidoVendaCarregamentoModificarSaldo_Unit.pas' {BI_PedidoVendaCarregamentoModificarSaldo},
  BI_PedidoVendaCarregamentoOBS_Unit in 'Forms\Comercial\PedidoDeVenda\BI_PedidoVendaCarregamentoOBS_Unit.pas' {BI_PedidoVendaCarregamentoOBS},
  BI_PedidoVendaEstrutura_Unit in 'Forms\Comercial\PedidoDeVenda\BI_PedidoVendaEstrutura_Unit.pas' {BI_PedidoVendaEstrutura},
  BI_PedidoVendaEstruturaBuscarProduto_Unit in 'Forms\Comercial\PedidoDeVenda\BI_PedidoVendaEstruturaBuscarProduto_Unit.pas' {BI_PedidoVendaEstrutura_BuscarProduto},
  BI_PedidoVendaFiltroCliente_Unit in 'Forms\Comercial\PedidoDeVenda\BI_PedidoVendaFiltroCliente_Unit.pas' {BI_PedidoVenda_FiltroCliente},
  BI_PedidoVendaFiltroTransportadora_Unit in 'Forms\Comercial\PedidoDeVenda\BI_PedidoVendaFiltroTransportadora_Unit.pas' {BI_PedidoVenda_FiltroTransportadora},
  BI_PedidoVendaItensPedidosxEstoque_Unit in 'Forms\Comercial\PedidoDeVenda\BI_PedidoVendaItensPedidosxEstoque_Unit.pas' {BI_PedidoVenda_ItensPedidosxEstoque},
  BI_PedidoVendaLogDataPCP_Unit in 'Forms\Comercial\PedidoDeVenda\BI_PedidoVendaLogDataPCP_Unit.pas' {BI_PedidoVendaLogDataPCP},
  SysAtualizarStorecProcedure_Unit in 'Estrutura\SysAtualizarStorecProcedure_Unit.pas' {Sys_AtualizarStorecProcedure},
  CertificadoQualidade_Unit in 'Forms\Comercial\CertificadoQualidade_CIT\CertificadoQualidade_Unit.pas' {CertificadoDeQualidade},
  CIT_CertificadoDeQualidade_Unit in 'Forms\Comercial\CertificadoQualidade_CIT\CIT_CertificadoDeQualidade_Unit.pas' {CIT_CertificadoDeQualidade},
  CIT_CertificadoDeQualidadeConsultarLotes_Unit in 'Forms\Comercial\CertificadoQualidade_CIT\CIT_CertificadoDeQualidadeConsultarLotes_Unit.pas' {CIT_CertificadoDeQualidade_ConsultarLotes},
  CIT_EnviarEmail_Unit in 'Forms\Comercial\CertificadoQualidade_CIT\CIT_EnviarEmail_Unit.pas' {CIT_EnviarEmail},
  CIT_IncluirDataPrevista in 'Forms\Comercial\CertificadoQualidade_CIT\CIT_IncluirDataPrevista.pas' {Incluir_DataPrevista},
  cit_unit in 'Forms\Comercial\CertificadoQualidade_CIT\cit_unit.pas' {CIT},
  ImpressaoCracha_Unit in 'Forms\GestaoPessoal\ImpressaoCracha_Unit.pas' {ImpressaoCracha},
  OrdemProducaoImprimirEtiquetaApontamento_Unit in 'Forms\Producao\EtiquetaApontamento\OrdemProducaoImprimirEtiquetaApontamento_Unit.pas' {OrdemProducao_ImprimirEtiquetaApontamento},
  DiarioTransportadora_Unit in 'Forms\Comercial\Faturamento\DiarioTransportadora_Unit.pas' {DiarioTransportadora},
  CorrigirQtdeEmbalagens_Unit in 'Forms\Producao\EtiquetaPequena\CorrigirQtdeEmbalagens_Unit.pas' {OrdemProducao_ImprimirEtiquetaADM},
  CorrigirQtdeEmbalagensModificar_Unit in 'Forms\Producao\EtiquetaPequena\CorrigirQtdeEmbalagensModificar_Unit.pas' {OrdemProducao_CorrigirQtdeEmbalagensModificar},
  ImprimirEtiquetaPecaPadrao_Unit in 'Forms\Producao\EtiquetaPequena\ImprimirEtiquetaPecaPadrao_Unit.pas' {ImprimirEtiquetaPecaPadrao},
  OrdemProducaoEtiquetaPalete_Unit in 'Forms\Producao\EtiquetaPequena\OrdemProducaoEtiquetaPalete_Unit.pas' {OrdemProducao_EtiquetaPalete},
  bi_pcp_unit in 'Forms\Producao\OrdemProducao\bi_pcp_unit.pas' {BI_PCP},
  BI_PCPAglutinacaoMP_Unit in 'Forms\Producao\OrdemProducao\BI_PCPAglutinacaoMP_Unit.pas' {BI_PCPAglutinacaoMP},
  BI_PCPBuscadorInjetora_Unit in 'Forms\Producao\OrdemProducao\BI_PCPBuscadorInjetora_Unit.pas' {BI_PCP_ConsultarInjetora},
  BI_PCPEscolherRecursos_Unit in 'Forms\Producao\OrdemProducao\BI_PCPEscolherRecursos_Unit.pas' {BI_PCPEscolherRecursos},
  OrdemProducao_ImprimirOPArquivos_Unit in 'Forms\Producao\OrdemProducao\OrdemProducao_ImprimirOPArquivos_Unit.pas' {OrdemProducao_ImprimirOP_Arquivos},
  OrdemProducaoImprimirOP_Unit in 'Forms\Producao\OrdemProducao\OrdemProducaoImprimirOP_Unit.pas' {OrdemProducao_ImprimirOP},
  PosVenda_Unit in 'Forms\Comercial\PosVenda\PosVenda_Unit.pas' {PosVenda_Form},
  RelatorioPosVenda_Unit in 'Forms\Comercial\PosVenda\Relatorio\RelatorioPosVenda_Unit.pas' {RelatorioPosVenda},
  OrdemSolicitacaoMateriaPrimaBuscador_Unit in 'Forms\Producao\SolicitacaoMateriaPrima\OrdemSolicitacaoMateriaPrimaBuscador_Unit.pas' {OrdemSolicitacao_MateriaPrimaBuscador},
  OrdemSolicitacaoMateriaPrimaAdicionarProduto_Unit in 'Forms\Producao\SolicitacaoMateriaPrima\OrdemSolicitacaoMateriaPrimaAdicionarProduto_Unit.pas' {OrdemSolicitacaoMateriaPrima_AdicionarProduto},
  OrdemSolicitacaoMateriaPrimaAdicionarProdutoQtd_Unit in 'Forms\Producao\SolicitacaoMateriaPrima\OrdemSolicitacaoMateriaPrimaAdicionarProdutoQtd_Unit.pas' {OrdemSolicitacaoMateriaPrima_AdicionarProdutoQtd},
  OrdemSolicitacaoMateriaPrima_Unit in 'Forms\Producao\SolicitacaoMateriaPrima\OrdemSolicitacaoMateriaPrima_Unit.pas' {OrdemSolicitacao_MateriaPrima},
  RelatorioAprontamentoProducao_Unit in 'Forms\Producao\RelatorioApontamentoProducao\RelatorioAprontamentoProducao_Unit.pas' {Relatorio_ApontamentoProducao},
  RelatorioCit_Unit in 'Forms\Comercial\CertificadoQualidade_CIT\Relatorio\RelatorioCit_Unit.pas' {RelatorioCIT},
  RelatorioEstoque_Unit in 'Forms\Estoque\ControleEstoque\Relatorio\RelatorioEstoque_Unit.pas' {Relatorio_Estoque},
  ImprimirEspecificacaoTecnica_Unit in 'Forms\Comercial\CertificadoQualidade_CIT\Relatorio\ImprimirEspecificacaoTecnica_Unit.pas' {Relatorio_ImprimirEspecificacaoTecnica},
  RelatorioFaturamentoPeriodico_Unit in 'Forms\Comercial\RelatorioFaturamentoPeriodico\RelatorioFaturamentoPeriodico_Unit.pas' {Relatorio_FaturamentoPeriodico},
  RelatorioHorasImprodutivas_Unit in 'Forms\Producao\RelatorioHorasImprodutivas\RelatorioHorasImprodutivas_Unit.pas' {Relatorio_HorasImprodutivas},
  RelatorioImpressaoEnvelopeEtiquetaParaFeiras_Unit in 'Forms\Comercial\RelatorioEnvelopeParaFeiras\RelatorioImpressaoEnvelopeEtiquetaParaFeiras_Unit.pas' {RelatorioImpressaoEnvelopeEtiquetaParaFeiras},
  RelatorioMediaPrazoPagamento_Unit in 'Forms\Comercial\RelatorioMediaPrazoPagamento\RelatorioMediaPrazoPagamento_Unit.pas' {Relatorio_MediaPrazoPagamento},
  RelatorioPedidosAbertosDataPCPAtrasada_Unit in 'Forms\Comercial\RelatorioPedidosDataPCPAtrasada\RelatorioPedidosAbertosDataPCPAtrasada_Unit.pas' {RelatorioAnaliseDataPCP},
  RelatorioPeriodicoFaturamentoxProducao_Unit in 'Forms\Comercial\RelatorioPeriodicoFaturamentoxProducao\RelatorioPeriodicoFaturamentoxProducao_Unit.pas' {Relatorio_PeriodicoFaturamentoxProducao},
  RelatorioDePerdas_Unit in 'Forms\Producao\RelatorioDePerdas\RelatorioDePerdas_Unit.pas' {Relatorio_Perdas},
  RelatorioPosicaoEstoqueFaturamento_Unit in 'Forms\Producao\RelatorioPosicaoEstoqueFaturamento\RelatorioPosicaoEstoqueFaturamento_Unit.pas' {PosicaoEstoqueFaturamento},
  relatorioparamentrizadovendas_unit in 'Forms\Comercial\RelatorioParamentrizadoVendas\relatorioparamentrizadovendas_unit.pas' {RelatorioParametrizadoVendas},
  RelatorioParametrizadoVendasEnvioXML_Unit in 'Forms\Comercial\RelatorioParamentrizadoVendas\RelatorioParametrizadoVendasEnvioXML_Unit.pas' {RelatorioParametrizadoVendasEnvioXML},
  RelatorioRankingClientes_Unit in 'Forms\Comercial\RelatorioRankingClientes\RelatorioRankingClientes_Unit.pas' {RelatorioRankingClientes},
  RelatorioNotaFiscal_Unit in 'Forms\Comercial\RelatorioNotaFiscal\RelatorioNotaFiscal_Unit.pas' {Relatorio_NotaFiscalVenda},
  RelatorioVendasPorMixProdutos_Unit in 'Forms\Comercial\RelatorioVendasPorMixProdutos\RelatorioVendasPorMixProdutos_Unit.pas' {RelatorioVendasPorMixProdutos},
  RelatorioApontamentoProducaoPorTurno_Unit in 'Forms\Producao\RelatorioApontamentoProducao\RelatorioApontamentoProducaoPorTurno_Unit.pas' {Relatorio_ApontamentoProducaoPorTurno},
  SysSetorBuscadorEmpresa_Unit in 'Estrutura\SysSetorBuscadorEmpresa_Unit.pas' {Sys_SetorBuscadorEmpresa},
  OrdemSeparacaoArquivos_Unit in 'Forms\Comercial\OrdemSeparacao\OrdemSeparacaoArquivos_Unit.pas' {OrdemSeparacao_Arquivos},
  OrdemSeparacaoArquivosModificarQuantidade_Unit in 'Forms\Comercial\OrdemSeparacao\OrdemSeparacaoArquivosModificarQuantidade_Unit.pas' {OrdemSeparacao_Arquivos_ModificarQuantidade},
  CIT_Inserir_Unit in 'Forms\Comercial\CertificadoQualidade_CIT\CIT_Inserir_Unit.pas' {CIT_Inserir},
  CIT_InserirTransportadora_Unit in 'Forms\Comercial\CertificadoQualidade_CIT\CIT_InserirTransportadora_Unit.pas' {CIT_Inserir_Transportadora},
  CIT_InserirMotorista_Unit in 'Forms\Comercial\CertificadoQualidade_CIT\CIT_InserirMotorista_Unit.pas' {CIT_Inserir_Motorista},
  Relatorio_ApontamentoProducaoAnalitico_Unit in 'Forms\Producao\RelatorioApontamentoProducao\Relatorio_ApontamentoProducaoAnalitico_Unit.pas' {Relatorio_ApontamentoProducaoAnalitico},
  CIT_Exclusao_Unit in 'Forms\Comercial\CertificadoQualidade_CIT\CIT_Exclusao_Unit.pas' {CIT_Exclusao},
  Relatorio_ApontamentoProducao_Filtros_Unit in 'Forms\Producao\RelatorioApontamentoProducao\Relatorio_ApontamentoProducao_Filtros_Unit.pas' {Relatorio_ApontamentoProducao_Filtros},
  OrdemSolicitacao_MateriaPrima_RelatorioConferencia_Unit in 'Forms\Producao\SolicitacaoMateriaPrima\OrdemSolicitacao_MateriaPrima_RelatorioConferencia_Unit.pas' {OrdemSolicitacao_MateriaPrima_RelatorioConferencia},
  RelatorioAprontamentoPersonalizacao_Unit in 'Forms\Producao\RelatorioAprontamentoPersonalizacao\RelatorioAprontamentoPersonalizacao_Unit.pas' {Relatorio_ApontamentoPersonalizacao},
  Relatorio_ApontamentoPersonalizacaoAnalitico_Unit in 'Forms\Producao\RelatorioAprontamentoPersonalizacao\Relatorio_ApontamentoPersonalizacaoAnalitico_Unit.pas' {Relatorio_ApontamentoPersonalizacaoAnalitico},
  CIT_CertificadoDeQualidade_ConsultarLotesQuantidade_Unit in 'Forms\Comercial\CertificadoQualidade_CIT\CIT_CertificadoDeQualidade_ConsultarLotesQuantidade_Unit.pas' {CIT_CertificadoDeQualidade_ConsultarLotesQuantidade},
  relatorioparametrizadovendasnovo_unit in 'Forms\Comercial\RelatorioParametrizadoVendasNOVO\relatorioparametrizadovendasnovo_unit.pas' {RelatorioParametrizadoVendasNOVO},
  relatorioparametrizadovendasnovo_filtros_unit in 'Forms\Comercial\RelatorioParametrizadoVendasNOVO\relatorioparametrizadovendasnovo_filtros_unit.pas' {RelatorioParametrizadoVendasNOVO_Filtros},
  RelatorioParametrizadoVendas_GerenciaXGerencia_Unit in 'Forms\Comercial\RelatorioParametrizadoVendasNOVO\RelatorioParametrizadoVendas_GerenciaXGerencia_Unit.pas' {RelatorioParametrizadoVendas_GerenciaXGerencia},
  RelatorioParametrizadoVendas_VendedorXVendedor_Unit in 'Forms\Comercial\RelatorioParametrizadoVendasNOVO\RelatorioParametrizadoVendas_VendedorXVendedor_Unit.pas' {RelatorioParametrizadoVendas_VendedorXVendedor},
  RelatorioParametrizadoVendas_ItemXItem_Unit in 'Forms\Comercial\RelatorioParametrizadoVendasNOVO\RelatorioParametrizadoVendas_ItemXItem_Unit.pas' {RelatorioParametrizadoVendas_ItemXItem},
  RelatorioPosicaoEstoque_Unit in 'Forms\Producao\RelatorioPosicaoEstoque\RelatorioPosicaoEstoque_Unit.pas' {Relatorio_PosicaoEstoque},
  RelatorioPosicaoEstoque_AcompanhamentoItens_Unit in 'Forms\Producao\RelatorioPosicaoEstoque\RelatorioPosicaoEstoque_AcompanhamentoItens_Unit.pas' {Relatorio_PosicaoEstoque_AcompanhamentoItens},
  RelatorioPosicaoEstoqueSaldo_Unit in 'Forms\Producao\RelatorioPosicaoEstoque\RelatorioPosicaoEstoqueSaldo_Unit.pas' {Relatorio_PosicaoEstoque_Saldo},
  RelatorioParametrizadoVendas_NotaXNota_Unit in 'Forms\Comercial\RelatorioParametrizadoVendasNOVO\RelatorioParametrizadoVendas_NotaXNota_Unit.pas' {RelatorioParametrizadoVendas_NotaXNota},
  RelatorioParametrizadoVendas_ClienteXCliente_Unit in 'Forms\Comercial\RelatorioParametrizadoVendasNOVO\RelatorioParametrizadoVendas_ClienteXCliente_Unit.pas' {RelatorioParametrizadoVendas_ClienteXCliente},
  BI_RelacionamentoCliente_Unit in 'Forms\Comercial\Cliente\BI_RelacionamentoCliente_Unit.pas' {BI_RelacionamentoCliente},
  BI_RelacionamentoCliente_FiltroSegmento_Unit in 'Forms\Comercial\Cliente\BI_RelacionamentoCliente_FiltroSegmento_Unit.pas' {BI_RelacionamentoCliente_FiltroSegmento},
  BI_RelacionamentoCliente_FiltroSetorMercado_Unit in 'Forms\Comercial\Cliente\BI_RelacionamentoCliente_FiltroSetorMercado_Unit.pas' {BI_RelacionamentoCliente_FiltroSetorMercado},
  OrdemProducao_RelatoriosDaInjecaoADM_Unit in 'Forms\Producao\OrdemProducao\OrdemProducao_RelatoriosDaInjecaoADM_Unit.pas' {OrdemProducao_RelatoriosDaInjecaoADM},
  OrdemProducao_Imprimir_QtdParcial_Unit in 'Forms\Producao\OrdemProducao\OrdemProducao_Imprimir_QtdParcial_Unit.pas' {OrdemProducao_Imprimir_QtdParcial},
  PainelOrdensProducaoUltimosApontamentos_Unit in 'Forms\Producao\PainelOrdensProducaoUltimosApontamentos\PainelOrdensProducaoUltimosApontamentos_Unit.pas' {Painel_OrdensProducaoUltimosApontamentos},
  RelatorioControleRotulos_Unit in 'Forms\Comercial\RelatorioControleRotulos\RelatorioControleRotulos_Unit.pas' {Relatorio_ControleRotulos},
  RelatorioControleRotulos_SaldosRotulos_Unit in 'Forms\Comercial\RelatorioControleRotulos\RelatorioControleRotulos_SaldosRotulos_Unit.pas' {Relatorio_ControleRotulos_SaldosRotulos},
  RelatorioUltimoFaturamentoCliente_Unit in 'Forms\Comercial\RelatorioUltimoFaturamento\RelatorioUltimoFaturamentoCliente_Unit.pas' {RelatorioUltimoFaturamentoCliente},
  RelatorioUltimoFaturamentoClienteQuery_Unit in 'Forms\Comercial\RelatorioUltimoFaturamento\RelatorioUltimoFaturamentoClienteQuery_Unit.pas' {RelatorioUltimoFaturamentoCliente_Query},
  RelatorioUltimoFaturamentoProduto_Unit in 'Forms\Comercial\RelatorioUltimoFaturamento\RelatorioUltimoFaturamentoProduto_Unit.pas' {RelatorioUltimoFaturamentoProduto},
  RelatorioUltimoFaturamentoProdutoQuery_Unit in 'Forms\Comercial\RelatorioUltimoFaturamento\RelatorioUltimoFaturamentoProdutoQuery_Unit.pas' {RelatorioUltimoFaturamentoProduto_Query},
  relatorioparamentrizadovendas_item_x_item_unit in 'Forms\Comercial\RelatorioParamentrizadoVendas\relatorioparamentrizadovendas_item_x_item_unit.pas' {RelatorioParamentrizadoVendas_Item_X_Item},
  RelatorioAprontamentoPaletizacao_Unit in 'Forms\Producao\RelatorioAprontamentoPaletizacao\RelatorioAprontamentoPaletizacao_Unit.pas' {Relatorio_ApontamentoPaletizacao},
  Relatorio_ApontamentoPaletizacaoAnalitico_Unit in 'Forms\Producao\RelatorioAprontamentoPaletizacao\Relatorio_ApontamentoPaletizacaoAnalitico_Unit.pas' {Relatorio_ApontamentoPaletizacaoAnalitico},
  Relatorio_ApontamentoProducaoOEE_Unit in 'Forms\Producao\RelatorioApontamentoProducao\Relatorio_ApontamentoProducaoOEE_Unit.pas' {Relatorio_ApontamentoProducao_OEE},
  relatorio_apontamentoproducaomiguelanalitico_unit in 'Forms\Producao\RelatorioApontamentoProducao\relatorio_apontamentoproducaomiguelanalitico_unit.pas' {Relatorio_ApontamentoProducao_MiguelAnalitico},
  RelatorioMovimentosInternos_Unit in 'Forms\Producao\RelatorioMovimentosInternos\RelatorioMovimentosInternos_Unit.pas' {Relatorio_MovimentosInternos},
  RelatorioMovimentosInternos_Consulta_Unit in 'Forms\Producao\RelatorioMovimentosInternos\RelatorioMovimentosInternos_Consulta_Unit.pas' {RelatorioMovimentosInternos_Consulta},
  RelatorioEstoqueSoproControleLoop_Unit in 'Forms\Producao\RelatorioEstoqueSoproControleLoop\RelatorioEstoqueSoproControleLoop_Unit.pas' {RelatorioEstoqueSoproControleLoop},
  RelatorioTonelagemDiaria_Unit in 'Forms\Comercial\RelatorioTonelagemDiaria\RelatorioTonelagemDiaria_Unit.pas' {Relatorio_TonelagemDiaria},
  relatorioposicaoestoquesaldoperda_unit in 'forms\producao\relatorioposicaoestoque\relatorioposicaoestoquesaldoperda_unit.pas' {Relatorio_PosicaoEstoque_SaldoPerda},
  PecaPadraoOrdemProducao_Unit in 'forms\producao\pecapadrao\PecaPadraoOrdemProducao_Unit.pas' {PecaPadrao_OrdemProducao},
  ProcessoInspecao_Unit in 'forms\qualidade\ProcessoInspecao_Unit.pas' {ProcessoInspecao},
  ProcessoInspecaoIncluir_Unit in 'forms\qualidade\ProcessoInspecaoIncluir_Unit.pas' {ProcessoInspecao_Incluir},
  ProcessoInspecaoIncluirBuscarInspector_Unit in 'forms\qualidade\ProcessoInspecaoIncluirBuscarInspector_Unit.pas' {ProcessoInspecao_IncluirBuscarInspector},
  ProcessoInspecaoIncluirBuscarProducao_Unit in 'forms\qualidade\ProcessoInspecaoIncluirBuscarProducao_Unit.pas' {ProcessoInspecao_IncluirBuscarProducao},
  ProcessoInspecaoIncluirBuscarDefeitos_Unit in 'forms\qualidade\ProcessoInspecaoIncluirBuscarDefeitos_Unit.pas' {ProcessoInspecao_IncluirBuscarDefeitos},
  ProcessoInspecaoIncluirBuscarDefeitosEmLinha_Unit in 'forms\qualidade\ProcessoInspecaoIncluirBuscarDefeitosEmLinha_Unit.pas' {ProcessoInspecao_IncluirBuscarDefeitosEmLinha},
  ProcessoInspecaoIncluirBuscarDefeitosFardo_Unit in 'forms\qualidade\ProcessoInspecaoIncluirBuscarDefeitosFardo_Unit.pas' {ProcessoInspecao_IncluirBuscarDefeitosFardo},
  BI_PCPMateriaPrimaProgramadaInjecao_Unit in 'forms\producao\ordemproducao\BI_PCPMateriaPrimaProgramadaInjecao_Unit.pas' {BI_PCP_MateriaPrimaProgramadaInjecao},
  ProcessoInspecaoObservacao_Unit in 'forms\qualidade\ProcessoInspecaoObservacao_Unit.pas' {ProcessoInspecao_Observacao},
  ProcessoInspecaoObservacao_Tipo_Unit in 'forms\qualidade\ProcessoInspecaoObservacao_Tipo_Unit.pas' {ProcessoInspecaoObservacao_Tipo},
  ProcessoInspecaoPainel_Unit in 'forms\qualidade\ProcessoInspecaoPainel_Unit.pas' {ProcessoInspecao_Painel},
  ProcessoInspecaoPainelDM_Unit in 'forms\qualidade\ProcessoInspecaoPainelDM_Unit.pas' {ProcessoInspecao_PainelDM: TDataModule},
  ControleE2_Unit in 'forms\estoque\ControleE2\ControleE2_Unit.pas' {ControleE2},
  OrdemProducao_ImprimirOP_ProducaoBomix_Unit in 'forms\producao\ordemproducao\OrdemProducao_ImprimirOP_ProducaoBomix_Unit.pas' {OrdemProducao_ImprimirOP_ProducaoBomix},
  funcaografica_unit in 'funcao\funcaografica_unit.pas' {Sys_FuncaoGrafica},
  OrdemProducao_ImprimirOP_Personalizacao_Unit in 'forms\producao\ordemproducao\OrdemProducao_ImprimirOP_Personalizacao_Unit.pas' {OrdemProducao_ImprimirOP_Personalizacao},
  cit_certificadodequalidade_bomix_unit in 'forms\comercial\certificadoqualidade_cit\cit_certificadodequalidade_bomix_unit.pas' {CIT_CertificadoDeQualidade_BOMIX},
  BI_PedidoVenda_Excel_PedidoAberto_Unit in 'forms\comercial\pedidodevenda\BI_PedidoVenda_Excel_PedidoAberto_Unit.pas' {BI_PedidoVenda_Excel_PedidoAberto},
  manutencaooperaces_unit in 'forms\producao\manutencaooperaces\manutencaooperaces_unit.pas' {ManuntecaoOperacoes},
  relatoriocontrolerotulos_porcliente_unit in 'forms\comercial\relatoriocontrolerotulos\relatoriocontrolerotulos_porcliente_unit.pas' {Relatorio_ControleRotulos_PorCliente},
  PcpAdministracaoResina_unit in 'forms\producao\AdministracaoMasterResina\PcpAdministracaoResina_unit.pas' {PcpAdministracaoMasterResina_Resina},
  PcpAdministracaoMasterResina_Unit in 'forms\producao\AdministracaoMasterResina\PcpAdministracaoMasterResina_Unit.pas' {PcpAdministracaoMasterResina},
  bi_pcp_EtiquetaInjetora_unit in 'forms\producao\ordemproducao\bi_pcp_EtiquetaInjetora_unit.pas' {BI_PCP_EtiquetaInjetora: TDataModule},
  BI_PCP_DataAjustada1diaDataPCP_unit in 'forms\producao\ordemproducao\BI_PCP_DataAjustada1diaDataPCP_unit.pas' {BI_PCP_DataAjustada1diaDataPCP},
  OrdemProducaoImprimirEtiquetaApontamentoConsultarSolictarPerdaWMS_unit in 'forms\producao\etiquetaapontamento\OrdemProducaoImprimirEtiquetaApontamentoConsultarSolictarPerdaWMS_unit.pas' {OrdemProducao_ImprimirEtiquetaApontamento_GerarConsultaWMS},
  ordemseparacaoarquivos_definidocas_unit in 'forms\comercial\ordemseparacao\ordemseparacaoarquivos_definidocas_unit.pas' {OrdemSeparacao_Arquivos_DefinirDocas},
  Relatorio_ApontamentoProducao_QuantidadeCicloMolde_Unit in 'forms\producao\relatorioapontamentoproducao\Relatorio_ApontamentoProducao_QuantidadeCicloMolde_Unit.pas' {Relatorio_ApontamentoProducao_QuantidadeCicloMolde},
  TransferenciaProducoes_CT_Unit in 'forms\estoque\Transferencia_Producoes_CT\TransferenciaProducoes_CT_Unit.pas' {TransferenciaProducoes_CT},
  BI_RastreabilidadeInsumo_Unit in 'forms\producao\Rastreabilidade\BI_RastreabilidadeInsumo_Unit.pas' {BI_RastreabilidadeInsumo},
  BI_FuncionarioEntregaMaterias_Unit in 'forms\gestaopessoal\BI_FuncionarioEntregaMaterias\BI_FuncionarioEntregaMaterias_Unit.pas' {BI_FuncionarioEntregaMaterias},
  BI_FuncionarioEntregaMaterias_InserirMaterial_Unit in 'forms\gestaopessoal\BI_FuncionarioEntregaMaterias\BI_FuncionarioEntregaMaterias_InserirMaterial_Unit.pas' {BI_FuncionarioEntregaMaterias_InserirMaterial},
  BI_FuncionarioEntregaMaterias_InserirMaterialQtd_Unit in 'forms\gestaopessoal\BI_FuncionarioEntregaMaterias\BI_FuncionarioEntregaMaterias_InserirMaterialQtd_Unit.pas' {BI_FuncionarioEntregaMaterias_InserirMaterialQtd},
  SolicitacaoCadastroProduto_Unit in 'forms\qualidade\SolicitacaoCadastroProduto\SolicitacaoCadastroProduto_Unit.pas' {SolicitacaoCadastroProduto},
  PecaPadrao_Unit in 'forms\qualidade\PecaPadrao\PecaPadrao_Unit.pas' {PecaPadrao},
  PecaPadrao_ImprimirPecaPadrao_Unit in 'forms\qualidade\PecaPadrao\PecaPadrao_ImprimirPecaPadrao_Unit.pas' {PecaPadrao_ImprimirPecaPadrao},
  PecaPadraoEnderecamento_Unit in 'forms\qualidade\PecaPadrao\PecaPadraoEnderecamento_Unit.pas' {PecaPadrao_Enderecamento},
  ordemsolicitacaomateriaprima_ImprimirEtiqueta_unit in 'forms\producao\solicitacaomateriaprima\ordemsolicitacaomateriaprima_ImprimirEtiqueta_unit.pas' {OrdemSolicitacao_MateriaPrima_ImprimirEtiqueta},
  ordemsolicitacaomateriaprima_ImprimirEtiquetaQtd_unit in 'forms\producao\solicitacaomateriaprima\ordemsolicitacaomateriaprima_ImprimirEtiquetaQtd_unit.pas' {Ordemsolicitacaomateriaprima_ImprimirEtiquetaQtd},
  OrdemProducao_ImprimirEtiquetaApontamento_CorrigirDados_Unit in 'forms\producao\etiquetaapontamento\OrdemProducao_ImprimirEtiquetaApontamento_CorrigirDados_Unit.pas' {OrdemProducao_ImprimirEtiquetaApontamento_CorrigirDados},
  BI_PedidoVendaQuebraReserva_Unit in 'forms\comercial\pedidodevenda\BI_PedidoVendaQuebraReserva_Unit.pas' {BI_PedidoVendaQuebraReserva},
  ordemproducao_imprimiretiquetasopro_uni1 in 'forms\producao\etiquetasopro\ordemproducao_imprimiretiquetasopro_uni1.pas' {OrdemProducao_ImprimirEtiquetaSopro},
  CertificadoDeQualidadeCadastro_Unit in 'forms\qualidade\CertificadoQualidade\CertificadoDeQualidadeCadastro_Unit.pas' {CertificadoDeQualidade_Cadastro},
  BI_FuncionarioEntregaMaterias_DataEntrega_Unit in 'forms\gestaopessoal\BI_FuncionarioEntregaMaterias\BI_FuncionarioEntregaMaterias_DataEntrega_Unit.pas' {BI_FuncionarioEntregaMaterias_DataEntrega},
  Relatorio_ControleRotulos_ExportarExcel_Unit in 'forms\comercial\relatoriocontrolerotulos\Relatorio_ControleRotulos_ExportarExcel_Unit.pas' {Relatorio_ControleRotulos_ExportarExcel},
  Relatorio_ApontamentoPersonalizacaoOEE_Unit in 'forms\producao\relatorioaprontamentopersonalizacao\Relatorio_ApontamentoPersonalizacaoOEE_Unit.pas' {RelatorioApontamentoPersonalizacaoOEE},
  CorrecaoApontamentoParada_Unit in 'forms\producao\CorrecaoApontamentoParada\CorrecaoApontamentoParada_Unit.pas' {CorrecaoApontamentoParada},
  CorrecaoApontamentoParada_Apontamento_Unit in 'forms\producao\CorrecaoApontamentoParada\CorrecaoApontamentoParada_Apontamento_Unit.pas' {CorrecaoApontamentoParada_Apontamento},
  RelatorioMapeamentoAnualVendas_Unit in 'forms\comercial\RelatorioMapeamentoAnualVendas\RelatorioMapeamentoAnualVendas_Unit.pas' {RelatorioMapaAnualVendas},
  RelatorioMapeamentoAnualVendasPorVendedor_Unit in 'forms\comercial\RelatorioMapeamentoAnualVendas\RelatorioMapeamentoAnualVendasPorVendedor_Unit.pas' {RelatorioMapaAnualVendasPorVendedor},
  RelatorioMapeamentoAnualVendasPorGerente_Unit in 'forms\comercial\RelatorioMapeamentoAnualVendas\RelatorioMapeamentoAnualVendasPorGerente_Unit.pas' {RelatorioMapaAnualVendasPorGerente},
  RelatorioMapeamentoAnualVendasPesoPorGerente_Unit in 'forms\comercial\RelatorioMapeamentoAnualVendas\RelatorioMapeamentoAnualVendasPesoPorGerente_Unit.pas' {RelatorioMapaAnualVendasPesoPorGerente},
  RelatorioMapeamentoAnualVendasPesoPorVendedor_Unit in 'forms\comercial\RelatorioMapeamentoAnualVendas\RelatorioMapeamentoAnualVendasPesoPorVendedor_Unit.pas' {RelatorioMapaAnualVendasPesoPorVendedor},
  OrdemProducao_ImprimirOP_TinturaBomix_Unit in 'forms\producao\ordemproducao\OrdemProducao_ImprimirOP_TinturaBomix_Unit.pas' {OrdemProducao_ImprimirOP_TinturaBomix},
  ConfiguracaoMolde_Unit in 'forms\qualidade\GrupoItemXMolde\ConfiguracaoMolde_Unit.pas' {ConfiguracaoMolde},
  ConfiguracaoMolde_VincularItem_Unit in 'forms\qualidade\GrupoItemXMolde\ConfiguracaoMolde_VincularItem_Unit.pas' {ConfiguracaoMolde_VincularItem},
  ConfiguracaoMolde_VincularCavidade_Unit in 'forms\qualidade\GrupoItemXMolde\ConfiguracaoMolde_VincularCavidade_Unit.pas' {ConfiguracaoMolde_VincularCavidade},
  ConfiguracaoMolde_Buscador_Unit in 'forms\qualidade\GrupoItemXMolde\ConfiguracaoMolde_Buscador_Unit.pas' {ConfiguracaoMolde_Buscador},
  ColetaSemanal_Unit in 'forms\qualidade\ColetaSemanal\ColetaSemanal_Unit.pas' {ColetaSemanal},
  ColetaSemanal_NovaColeta_Unit in 'forms\qualidade\ColetaSemanal\ColetaSemanal_NovaColeta_Unit.pas' {ColetaSemanal_NovaColeta},
  RelatorioPrimeiroFaturamentoClienteQuery_Unit in 'forms\comercial\relatorioultimofaturamento\RelatorioPrimeiroFaturamentoClienteQuery_Unit.pas' {RelatorioPrimeiroFaturamentoCliente_Query},
  ColetaSemanal_NovaColetaQTD_Unit in 'forms\qualidade\ColetaSemanal\ColetaSemanal_NovaColetaQTD_Unit.pas' {ColetaSemanal_NovaColetaQtd},
  BI_RastreabilidadeInsumo_Notas_Unit in 'forms\producao\Rastreabilidade\BI_RastreabilidadeInsumo_Notas_Unit.pas' {BI_RastreabilidadeInsumo_Notas},
  BI_RastreabilidadeInsumo_OP_Unit in 'forms\producao\Rastreabilidade\BI_RastreabilidadeInsumo_OP_Unit.pas' {BI_RastreabilidadeInsumo_Ops},
  ColetaSemanal_RelatorioSemanal_Unit in 'forms\qualidade\ColetaSemanal\ColetaSemanal_RelatorioSemanal_Unit.pas' {ColetaSemanal_RelatorioSemanal},
  ComissaoVenda_Unit in 'forms\comercial\ComissaoVendas\ComissaoVenda_Unit.pas' {RelatorioComissaoVenda},
  TesteEspessura_Unit in 'forms\qualidade\TesteEspessura\TesteEspessura_Unit.pas' {Teste_Espessura},
  TestesQualidade_Unit in 'forms\qualidade\TestesQualidade\TestesQualidade_Unit.pas' {TesteQualidade},
  RelatorioComissaoVenda_Analitico_Unit in 'forms\comercial\ComissaoVendas\RelatorioComissaoVenda_Analitico_Unit.pas' {RelatorioComissaoVenda_Analitico},
  Teste_Espessura_Configuracao_Unit in 'forms\qualidade\TesteEspessura\Teste_Espessura_Configuracao_Unit.pas' {Teste_Espessura_Configuracao},
  Teste_Espessura_ConfiguracaoBuscador_Unit in 'forms\qualidade\TesteEspessura\Teste_Espessura_ConfiguracaoBuscador_Unit.pas' {Teste_Espessura_ConfiguracaoBuscador},
  Teste_Espessura_Configuracao_AdicionarMedidda_Unit in 'forms\qualidade\TesteEspessura\Teste_Espessura_Configuracao_AdicionarMedidda_Unit.pas' {Teste_Espessura_Configuracao_AdicionarMedidda},
  Teste_Espessura_NovoTeste_Unit in 'forms\qualidade\TesteEspessura\Teste_Espessura_NovoTeste_Unit.pas' {Teste_Espessura_NovoTeste},
  ColetaSemanal_NovaColeta_FuncionarioBuscador_Unit in 'forms\qualidade\ColetaSemanal\ColetaSemanal_NovaColeta_FuncionarioBuscador_Unit.pas' {ColetaSemanal_NovaColeta_FuncionarioBuscador},
  Teste_Espessura_NovoTeste_SepararParaTeste_Unit in 'forms\qualidade\TesteEspessura\Teste_Espessura_NovoTeste_SepararParaTeste_Unit.pas' {Teste_Espessura_NovoTeste_SepararParaTeste},
  Teste_Espessura_NovoTeste_SepararParaTeste_FuncionarioBuscador_Unit in 'forms\qualidade\TesteEspessura\Teste_Espessura_NovoTeste_SepararParaTeste_FuncionarioBuscador_Unit.pas' {Teste_Espessura_NovoTeste_SepararParaTeste_FuncionarioBuscador},
  DM_TesteQualidade_GravarCapaComum_Unit in 'forms\qualidade\TestesQualidade\DM_TesteQualidade_GravarCapaComum_Unit.pas' {TesteQualidade_GravarCapaComum_DM: TDataModule},
  InspecaoQualidade_Unit in 'forms\qualidade\InspecaoQualidade\InspecaoQualidade_Unit.pas' {InspecaoQualidade},
  CadastroTipoDefeito_Unit in 'forms\qualidade\InspecaoQualidade\CadastroTipoDefeito_Unit.pas' {InspecaoQualidade_CadastroTipoDefeito},
  relatorioparamentrizadovendas_segmento_x_segmento_unit in 'forms\comercial\relatorioparamentrizadovendas\relatorioparamentrizadovendas_segmento_x_segmento_unit.pas' {RelatorioParamentrizadoVendas_Segmento_X_Segmento},
  relatorioparametrizadovendas_gerenciaxsegmento_unit in 'forms\comercial\relatorioparametrizadovendasnovo\relatorioparametrizadovendas_gerenciaxsegmento_unit.pas' {RelatorioParametrizadoVendas_GerenciaXSegmento},
  AdministracaoCiclo_Unit in 'forms\producao\AdministracaoCiclo\AdministracaoCiclo_Unit.pas' {AdministracaoCiclo},
  BI_PedidoVendaDao_Unit in 'forms\comercial\pedidodevenda\BI_PedidoVendaDao_Unit.pas' {BI_PedidoVenda_DAO: TDataModule},
  BI_PedidoVenda_ConsultarInsumos_Unit in 'forms\comercial\pedidodevenda\BI_PedidoVenda_ConsultarInsumos_Unit.pas' {BI_PedidoVenda_ConsultarInsumos},
  PesoInsumo_Unit in 'forms\estoque\PesoInsumo\PesoInsumo_Unit.pas' {PesoInsumo},
  CertificadoDeQualidadeCadastro_DefinicaoMetricas_Unit in 'forms\qualidade\CertificadoQualidade\CertificadoDeQualidadeCadastro_DefinicaoMetricas_Unit.pas' {CertificadoDeQualidadeCadastro_DefinicaoMetricas},
  ProdutoEstrutura_Unit in 'forms\producao\relatorioprodutoestrutura\ProdutoEstrutura_Unit.pas' {Relatorio_EstruturaProduto},
  BI_PedidoVenda_PedidosSemOP_Unit in 'forms\comercial\pedidodevenda\BI_PedidoVenda_PedidosSemOP_Unit.pas' {BI_PedidoVenda_PedidosSemOP},
  BI_RelacionamentoCliente_ExportarExcel_Unit in 'forms\comercial\cliente\BI_RelacionamentoCliente_ExportarExcel_Unit.pas' {BI_RelacionamentoCliente_ExportarExcel: TDataModule},
  BI_FuncionarioEntregaMaterias_FuncXMat_Unit in 'forms\gestaopessoal\BI_FuncionarioEntregaMaterias\BI_FuncionarioEntregaMaterias_FuncXMat_Unit.pas' {BI_FuncionarioEntregaMaterias_FuncXMat: TDataModule},
  CadastroAcessorios_EntregaMaterias_Unit in 'forms\gestaopessoal\BI_FuncionarioEntregaMaterias\CadastroAcessorios_EntregaMaterias_Unit.pas' {CadastroAcessosorios_EntregaMateriais},
  sys_usuariobuscadorfornecedor_unit in 'estrutura\sys_usuariobuscadorfornecedor_unit.pas' {Sys_UsuarioBuscadorFornecedor},
  BI_FuncionarioEntregaMaterias_MateriasAgrupadoPorMes_Unit in 'forms\gestaopessoal\BI_FuncionarioEntregaMaterias\BI_FuncionarioEntregaMaterias_MateriasAgrupadoPorMes_Unit.pas' {BI_FuncionarioEntregaMaterias_MateriasAgrupadoPorMes: TDataModule},
  padraobuscadorfiltro2_unit in 'padrao\padraobuscadorfiltro2_unit.pas' {PadraoBuscadorFiltro2},
  RelatorioComparativoVendasAnuais_Unit in 'forms\comercial\RelatorioComparativoVendasAnuais\RelatorioComparativoVendasAnuais_Unit.pas' {Relatorio_ComparativoVendasAnuais};

{$R *.res}

begin

  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.Title := 'Bomix BI';
  Application.CreateForm(TSys_Principal, Sys_Principal);
  Application.CreateForm(TSys_Inicializacao, Sys_Inicializacao);
  Application.CreateForm(TSys_ModuloConexaoDados, Sys_ModuloConexaoDados);
  Application.CreateForm(TSys_FuncaoRestricoesInformacoes, Sys_FuncaoRestricoesInformacoes);
  Application.CreateForm(TSys_FuncaoSistema, Sys_FuncaoSistema);
  Application.CreateForm(TSys_FuncaoGrafica, Sys_FuncaoGrafica);
  Application.CreateForm(TCertificadoDeQualidadeCadastro_DefinicaoMetricas, CertificadoDeQualidadeCadastro_DefinicaoMetricas);
  Application.Run;

end.
