unit OrdemProducao_ImprimirOPArquivos_Unit;

interface

uses
  Winapi.Windows, Winapi.Messages, System.SysUtils, System.Variants, System.Classes, Vcl.Graphics,
  Vcl.Controls, Vcl.Forms, Vcl.Dialogs, ppDBBDE, ppBands, ppReport, ppStrtch,
  ppSubRpt, Data.DB, ppDB, Datasnap.DBClient, Data.Win.ADODB, Datasnap.Provider,
  ppParameter, ppDesignLayer, ppClass, ppBarCod, ppCtrls, ppPrnabl, ppCache,
  ppProd, ppComm, ppRelatv, ppDBPipe, ppModule, raCodMod, Vcl.StdCtrls, ppMemo,
  dxGDIPlusClasses;

type
  TOrdemProducao_ImprimirOP_Arquivos = class(TForm)
    ppDBPipeline2: TppDBPipeline;
    CDS_ImpressaoPersonalizacaoOP: TClientDataSet;
    Query_ImpressaoPersonalizacaoOP: TADOQuery;
    DS_ImpressaoPersonalizacaoOP: TDataSource;
    DSP_ImpressaoPersonalizacaoOP: TDataSetProvider;
    ppImprimirPersonalizacao: TppReport;
    ppHeaderBand1: TppHeaderBand;
    ppShape275: TppShape;
    ppImage1: TppImage;
    ppLabel90: TppLabel;
    ppLine9: TppLine;
    ppLabel98: TppLabel;
    ppLabel99: TppLabel;
    ppLabel100: TppLabel;
    ppDBText7: TppDBText;
    ppDBText12: TppDBText;
    ppDBText13: TppDBText;
    ppDBBarCode4: TppDBBarCode;
    ppShape399: TppShape;
    ppLabel153: TppLabel;
    ppDBText22: TppDBText;
    ppDBText23: TppDBText;
    ppLabel154: TppLabel;
    ppLabel155: TppLabel;
    ppLabel156: TppLabel;
    ppLabel157: TppLabel;
    ppDBText24: TppDBText;
    ppDBText25: TppDBText;
    ppDBText26: TppDBText;
    ppDBText27: TppDBText;
    ppLabel158: TppLabel;
    ppLabel159: TppLabel;
    ppDBBarCode7: TppDBBarCode;
    ppLabel160: TppLabel;
    ppLabel161: TppLabel;
    ppDBText19: TppDBText;
    ppLabel101: TppLabel;
    ppDBText20: TppDBText;
    ppLabel102: TppLabel;
    ppDBText37: TppDBText;
    ppLabel460: TppLabel;
    ppLabel462: TppLabel;
    ppLabel463: TppLabel;
    ppLabel461: TppLabel;
    ppLabel464: TppLabel;
    ppDBText21: TppDBText;
    ppDBText39: TppDBText;
    ppDBText38: TppDBText;
    ppDetailBand2: TppDetailBand;
    ppLine10: TppLine;
    ppDBText32: TppDBText;
    ppDBText33: TppDBText;
    ppDBText34: TppDBText;
    ppDBText35: TppDBText;
    ppDBText31: TppDBText;
    ppDBText36: TppDBText;
    ppFooterBand2: TppFooterBand;
    ppLine16: TppLine;
    ppLine17: TppLine;
    ppLabel164: TppLabel;
    ppLBL_UsuarioPersonalizacao: TppLabel;
    ppLBL_DataPersonalizacao: TppLabel;
    ppDBBarCode6: TppDBBarCode;
    ppLabel111: TppLabel;
    ppLabel113: TppLabel;
    ppShape442: TppShape;
    ppLabel142: TppLabel;
    ppShape483: TppShape;
    ppLabel147: TppLabel;
    ppShape484: TppShape;
    ppLabel148: TppLabel;
    ppShape457: TppShape;
    ppShape458: TppShape;
    ppShape459: TppShape;
    ppShape460: TppShape;
    ppLabel168: TppLabel;
    ppLabel169: TppLabel;
    ppLabel170: TppLabel;
    ppShape462: TppShape;
    ppShape464: TppShape;
    ppShape465: TppShape;
    ppLabel171: TppLabel;
    ppLabel172: TppLabel;
    ppLabel173: TppLabel;
    ppShape466: TppShape;
    ppLabel174: TppLabel;
    ppLabel175: TppLabel;
    ppLabel176: TppLabel;
    ppLabel177: TppLabel;
    ppShape447: TppShape;
    ppShape449: TppShape;
    ppLabel167: TppLabel;
    ppShape453: TppShape;
    ppLabel180: TppLabel;
    ppShape454: TppShape;
    ppShape455: TppShape;
    ppLabel181: TppLabel;
    ppShape456: TppShape;
    ppLabel182: TppLabel;
    ppShape470: TppShape;
    ppShape471: TppShape;
    ppLabel183: TppLabel;
    ppShape477: TppShape;
    ppShape478: TppShape;
    ppShape479: TppShape;
    ppLabel186: TppLabel;
    ppShape480: TppShape;
    ppShape481: TppShape;
    ppLabel187: TppLabel;
    ppShape489: TppShape;
    ppShape490: TppShape;
    ppShape491: TppShape;
    ppLabel190: TppLabel;
    ppShape492: TppShape;
    ppShape493: TppShape;
    ppLabel191: TppLabel;
    ppShape499: TppShape;
    ppShape500: TppShape;
    ppShape501: TppShape;
    ppLabel194: TppLabel;
    ppShape502: TppShape;
    ppShape503: TppShape;
    ppLabel195: TppLabel;
    ppShape509: TppShape;
    ppShape510: TppShape;
    ppShape511: TppShape;
    ppLabel198: TppLabel;
    ppShape512: TppShape;
    ppShape513: TppShape;
    ppLabel199: TppLabel;
    ppShape519: TppShape;
    ppShape520: TppShape;
    ppShape521: TppShape;
    ppLabel202: TppLabel;
    ppShape522: TppShape;
    ppShape523: TppShape;
    ppLabel203: TppLabel;
    ppShape529: TppShape;
    ppShape530: TppShape;
    ppShape531: TppShape;
    ppLabel206: TppLabel;
    ppShape532: TppShape;
    ppShape533: TppShape;
    ppLabel207: TppLabel;
    ppShape539: TppShape;
    ppShape540: TppShape;
    ppShape541: TppShape;
    ppLabel210: TppLabel;
    ppShape542: TppShape;
    ppShape543: TppShape;
    ppLabel211: TppLabel;
    ppShape1683: TppShape;
    ppShape1684: TppShape;
    ppShape1685: TppShape;
    ppLabel214: TppLabel;
    ppShape1686: TppShape;
    ppShape1687: TppShape;
    ppLabel215: TppLabel;
    ppShape1693: TppShape;
    ppShape1694: TppShape;
    ppShape1695: TppShape;
    ppLabel218: TppLabel;
    ppShape1696: TppShape;
    ppShape1697: TppShape;
    ppLabel219: TppLabel;
    ppShape1703: TppShape;
    ppShape1704: TppShape;
    ppShape1705: TppShape;
    ppLabel222: TppLabel;
    ppShape1706: TppShape;
    ppShape1707: TppShape;
    ppLabel223: TppLabel;
    ppShape1713: TppShape;
    ppShape1714: TppShape;
    ppShape1715: TppShape;
    ppLabel226: TppLabel;
    ppShape1716: TppShape;
    ppShape1717: TppShape;
    ppLabel227: TppLabel;
    ppShape1723: TppShape;
    ppShape1724: TppShape;
    ppSummaryBand3: TppSummaryBand;
    ppSubReport2: TppSubReport;
    ppChildReport2: TppChildReport;
    ppTitleBand2: TppTitleBand;
    ppLabel257: TppLabel;
    ppDetailBand3: TppDetailBand;
    ppFooterBand3: TppFooterBand;
    ppSummaryBand4: TppSummaryBand;
    ppDesignLayers2: TppDesignLayers;
    ppDesignLayer2: TppDesignLayer;
    ppPageStyle1: TppPageStyle;
    ppGroup2: TppGroup;
    ppGroupHeaderBand2: TppGroupHeaderBand;
    ppShape278: TppShape;
    ppLabel103: TppLabel;
    ppLabel104: TppLabel;
    ppLabel105: TppLabel;
    ppLabel106: TppLabel;
    ppLabel107: TppLabel;
    ppLabel108: TppLabel;
    ppGroupFooterBand2: TppGroupFooterBand;
    ppDesignLayers3: TppDesignLayers;
    ppDesignLayer3: TppDesignLayer;
    ppDesignLayer4: TppDesignLayer;
    ppParameterList1: TppParameterList;
    ppBDEPipeline_Estrutura: TppBDEPipeline;
    ppShape1098: TppShape;
    ppImprimirPersonalizacaoHTD: TppReport;
    ppHeaderBand3: TppHeaderBand;
    ppShape50: TppShape;
    ppImage3: TppImage;
    ppLabel696: TppLabel;
    ppLine1: TppLine;
    ppLabel697: TppLabel;
    ppLabel698: TppLabel;
    ppLabel699: TppLabel;
    ppDBText54: TppDBText;
    ppDBText56: TppDBText;
    ppDBText57: TppDBText;
    ppDBBarCode3: TppDBBarCode;
    ppShape51: TppShape;
    ppLabel700: TppLabel;
    ppDBText58: TppDBText;
    ppDBText68: TppDBText;
    ppLabel701: TppLabel;
    ppLabel702: TppLabel;
    ppLabel703: TppLabel;
    ppLabel704: TppLabel;
    ppDBText69: TppDBText;
    ppDBText70: TppDBText;
    ppDBText71: TppDBText;
    ppDBText72: TppDBText;
    ppLabel705: TppLabel;
    ppLabel706: TppLabel;
    ppDBBarCode9: TppDBBarCode;
    ppLabel707: TppLabel;
    ppLabel708: TppLabel;
    ppDBText73: TppDBText;
    ppLabel709: TppLabel;
    ppDBText74: TppDBText;
    ppLabel710: TppLabel;
    ppDBText75: TppDBText;
    ppLabel711: TppLabel;
    ppLabel712: TppLabel;
    ppLabel713: TppLabel;
    ppLabel714: TppLabel;
    ppLabel715: TppLabel;
    ppDBText76: TppDBText;
    ppDBText77: TppDBText;
    ppDBText78: TppDBText;
    ppDetailBand7: TppDetailBand;
    ppLine7: TppLine;
    ppDBText79: TppDBText;
    ppDBText80: TppDBText;
    ppDBText81: TppDBText;
    ppDBText82: TppDBText;
    ppDBText83: TppDBText;
    ppDBText84: TppDBText;
    ppFooterBand6: TppFooterBand;
    ppShape1310: TppShape;
    ppLine8: TppLine;
    ppLabel716: TppLabel;
    ppLine11: TppLine;
    ppLine25: TppLine;
    ppLine26: TppLine;
    ppLabel717: TppLabel;
    ppLabel718: TppLabel;
    ppDBText85: TppDBText;
    ppDBText86: TppDBText;
    ppDBText87: TppDBText;
    ppLabel719: TppLabel;
    ppLabel720: TppLabel;
    ppDBBarCode10: TppDBBarCode;
    ppLabel721: TppLabel;
    ppLabel722: TppLabel;
    ppShape1311: TppShape;
    ppLabel723: TppLabel;
    ppShape1312: TppShape;
    ppLabel724: TppLabel;
    ppShape1313: TppShape;
    ppLabel725: TppLabel;
    ppShape1320: TppShape;
    ppShape1321: TppShape;
    ppShape1322: TppShape;
    ppShape1323: TppShape;
    ppLabel726: TppLabel;
    ppLabel727: TppLabel;
    ppShape1324: TppShape;
    ppLabel728: TppLabel;
    ppShape1325: TppShape;
    ppShape1327: TppShape;
    ppShape1328: TppShape;
    ppLabel729: TppLabel;
    ppLabel730: TppLabel;
    ppLabel731: TppLabel;
    ppShape1329: TppShape;
    ppLabel732: TppLabel;
    ppLabel733: TppLabel;
    ppLabel734: TppLabel;
    ppLabel735: TppLabel;
    ppLabel736: TppLabel;
    ppShape1330: TppShape;
    ppLabel737: TppLabel;
    ppShape1331: TppShape;
    ppShape1337: TppShape;
    ppShape1339: TppShape;
    ppLabel749: TppLabel;
    ppShape1343: TppShape;
    ppLabel750: TppLabel;
    ppShape1344: TppShape;
    ppShape1345: TppShape;
    ppLabel751: TppLabel;
    ppShape1346: TppShape;
    ppLabel752: TppLabel;
    ppShape1347: TppShape;
    ppShape1348: TppShape;
    ppLabel753: TppLabel;
    ppShape1349: TppShape;
    ppShape1354: TppShape;
    ppShape1355: TppShape;
    ppShape1356: TppShape;
    ppLabel756: TppLabel;
    ppShape1357: TppShape;
    ppShape1358: TppShape;
    ppLabel757: TppLabel;
    ppShape1359: TppShape;
    ppShape1364: TppShape;
    ppShape1365: TppShape;
    ppShape1366: TppShape;
    ppLabel760: TppLabel;
    ppShape1367: TppShape;
    ppShape1368: TppShape;
    ppLabel761: TppLabel;
    ppShape1369: TppShape;
    ppShape1374: TppShape;
    ppShape1375: TppShape;
    ppShape1376: TppShape;
    ppLabel764: TppLabel;
    ppShape1377: TppShape;
    ppShape1378: TppShape;
    ppLabel765: TppLabel;
    ppShape1379: TppShape;
    ppShape1384: TppShape;
    ppShape1385: TppShape;
    ppShape1386: TppShape;
    ppLabel768: TppLabel;
    ppShape1387: TppShape;
    ppShape1388: TppShape;
    ppLabel769: TppLabel;
    ppShape1389: TppShape;
    ppShape1394: TppShape;
    ppShape1395: TppShape;
    ppShape1396: TppShape;
    ppLabel772: TppLabel;
    ppShape1397: TppShape;
    ppShape1398: TppShape;
    ppLabel773: TppLabel;
    ppShape1399: TppShape;
    ppShape1404: TppShape;
    ppShape1405: TppShape;
    ppShape1406: TppShape;
    ppLabel776: TppLabel;
    ppShape1407: TppShape;
    ppShape1408: TppShape;
    ppLabel777: TppLabel;
    ppShape1409: TppShape;
    ppShape1414: TppShape;
    ppShape1415: TppShape;
    ppShape1416: TppShape;
    ppLabel780: TppLabel;
    ppShape1417: TppShape;
    ppShape1418: TppShape;
    ppLabel781: TppLabel;
    ppShape1419: TppShape;
    ppShape1424: TppShape;
    ppShape1425: TppShape;
    ppLabel784: TppLabel;
    ppShape1427: TppShape;
    ppShape1428: TppShape;
    ppLabel785: TppLabel;
    ppShape1429: TppShape;
    ppShape1434: TppShape;
    ppShape1435: TppShape;
    ppLabel788: TppLabel;
    ppShape1437: TppShape;
    ppShape1438: TppShape;
    ppLabel789: TppLabel;
    ppShape1439: TppShape;
    ppShape1444: TppShape;
    ppShape1445: TppShape;
    ppLabel792: TppLabel;
    ppShape1447: TppShape;
    ppShape1448: TppShape;
    ppLabel793: TppLabel;
    ppShape1449: TppShape;
    ppShape1454: TppShape;
    ppShape1455: TppShape;
    ppPageStyle3: TppPageStyle;
    ppGroup5: TppGroup;
    ppGroupHeaderBand5: TppGroupHeaderBand;
    ppShape2004: TppShape;
    ppLabel1039: TppLabel;
    ppLabel1040: TppLabel;
    ppLabel1041: TppLabel;
    ppLabel1042: TppLabel;
    ppLabel1043: TppLabel;
    ppLabel1044: TppLabel;
    ppGroupFooterBand5: TppGroupFooterBand;
    ppDesignLayers8: TppDesignLayers;
    ppDesignLayer11: TppDesignLayer;
    ppDesignLayer12: TppDesignLayer;
    ppParameterList3: TppParameterList;
    ppLabel796: TppLabel;
    ppShape1456: TppShape;
    ppShape1457: TppShape;
    ppShape1462: TppShape;
    ppLabel799: TppLabel;
    ppShape1463: TppShape;
    ppShape1464: TppShape;
    ppLabel800: TppLabel;
    ppShape1466: TppShape;
    ppShape1467: TppShape;
    ppShape1472: TppShape;
    ppLabel803: TppLabel;
    ppShape1473: TppShape;
    ppShape1474: TppShape;
    ppLabel804: TppLabel;
    ppShape1476: TppShape;
    ppShape1477: TppShape;
    ppShape1482: TppShape;
    ppLabel807: TppLabel;
    ppShape1483: TppShape;
    ppShape1484: TppShape;
    ppLabel808: TppLabel;
    ppShape1486: TppShape;
    ppShape1487: TppShape;
    ppShape1492: TppShape;
    ppLabel811: TppLabel;
    ppShape1493: TppShape;
    ppShape1494: TppShape;
    ppLabel812: TppLabel;
    ppLabel813: TppLabel;
    ppLabel814: TppLabel;
    ppShape1426: TppShape;
    ppShape1436: TppShape;
    ppShape1446: TppShape;
    ppShape1495: TppShape;
    ppShape1485: TppShape;
    ppShape1475: TppShape;
    ppShape1465: TppShape;
    ppShape1326: TppShape;
    ppShape1332: TppShape;
    ppShape1333: TppShape;
    ppShape1334: TppShape;
    ppShape1335: TppShape;
    ppShape1336: TppShape;
    ppShape1338: TppShape;
    ppLabel739: TppLabel;
    ppShape1340: TppShape;
    ppShape1341: TppShape;
    ppLabel740: TppLabel;
    ppShape1342: TppShape;
    ppShape1350: TppShape;
    ppShape1351: TppShape;
    ppShape1352: TppShape;
    ppLabel741: TppLabel;
    ppShape1353: TppShape;
    ppShape1360: TppShape;
    ppLabel742: TppLabel;
    ppShape1361: TppShape;
    ppLabel743: TppLabel;
    ppShape1362: TppShape;
    ppShape1363: TppShape;
    ppLabel744: TppLabel;
    ppShape1370: TppShape;
    ppLabel745: TppLabel;
    ppShape1371: TppShape;
    ppShape1372: TppShape;
    ppLabel746: TppLabel;
    ppShape1373: TppShape;
    ppLabel747: TppLabel;
    ppLabel748: TppLabel;
    ppLabel754: TppLabel;
    ppLabel755: TppLabel;
    ppLabel758: TppLabel;
    ppLabel759: TppLabel;
    ppShape1380: TppShape;
    ppShape1381: TppShape;
    ppShape1382: TppShape;
    ppLabel762: TppLabel;
    ppLabel763: TppLabel;
    ppLabel766: TppLabel;
    ppShape1383: TppShape;
    ppShape1390: TppShape;
    ppShape1391: TppShape;
    ppShape1392: TppShape;
    ppShape1393: TppShape;
    ppShape1400: TppShape;
    ppLabel767: TppLabel;
    ppShape1401: TppShape;
    ppShape1402: TppShape;
    ppLabel770: TppLabel;
    ppShape1403: TppShape;
    ppShape1410: TppShape;
    ppShape1411: TppShape;
    ppShape1412: TppShape;
    ppLabel771: TppLabel;
    ppShape1413: TppShape;
    ppShape1420: TppShape;
    ppLabel774: TppLabel;
    ppShape1421: TppShape;
    ppShape1422: TppShape;
    ppShape1423: TppShape;
    ppShape1430: TppShape;
    ppLabel775: TppLabel;
    ppShape1431: TppShape;
    ppShape1432: TppShape;
    ppLabel778: TppLabel;
    ppShape1433: TppShape;
    ppShape1440: TppShape;
    ppShape1441: TppShape;
    ppShape1442: TppShape;
    ppLabel779: TppLabel;
    ppShape1443: TppShape;
    ppShape1450: TppShape;
    ppLabel782: TppLabel;
    ppShape1451: TppShape;
    ppShape1452: TppShape;
    ppShape1453: TppShape;
    ppShape1458: TppShape;
    ppLabel783: TppLabel;
    ppShape1459: TppShape;
    ppShape1460: TppShape;
    ppLabel786: TppLabel;
    ppShape1461: TppShape;
    ppShape1468: TppShape;
    ppShape1469: TppShape;
    ppLabel787: TppLabel;
    ppShape1470: TppShape;
    ppShape1471: TppShape;
    ppLabel790: TppLabel;
    ppShape1478: TppShape;
    ppShape1479: TppShape;
    ppShape1480: TppShape;
    ppLabel791: TppLabel;
    ppShape1481: TppShape;
    ppShape1488: TppShape;
    ppLabel794: TppLabel;
    ppShape1489: TppShape;
    ppShape1490: TppShape;
    ppShape1491: TppShape;
    ppLabel795: TppLabel;
    ppShape1496: TppShape;
    ppShape1497: TppShape;
    ppLabel797: TppLabel;
    ppShape1498: TppShape;
    ppShape1499: TppShape;
    ppShape1500: TppShape;
    ppShape1501: TppShape;
    ppLabel798: TppLabel;
    ppShape1502: TppShape;
    ppShape1503: TppShape;
    ppLabel801: TppLabel;
    ppShape1504: TppShape;
    ppShape1505: TppShape;
    ppShape1506: TppShape;
    ppShape1507: TppShape;
    ppLabel802: TppLabel;
    ppShape1508: TppShape;
    ppShape1509: TppShape;
    ppLabel805: TppLabel;
    ppShape1510: TppShape;
    ppShape1511: TppShape;
    ppShape1512: TppShape;
    ppLabel806: TppLabel;
    ppShape1513: TppShape;
    ppShape1514: TppShape;
    ppLabel809: TppLabel;
    ppShape1515: TppShape;
    ppShape1516: TppShape;
    ppShape1517: TppShape;
    ppLabel810: TppLabel;
    ppShape1518: TppShape;
    ppShape1519: TppShape;
    ppLabel815: TppLabel;
    ppShape1520: TppShape;
    ppShape1521: TppShape;
    ppShape1522: TppShape;
    ppLabel816: TppLabel;
    ppShape1523: TppShape;
    ppShape1524: TppShape;
    ppLabel817: TppLabel;
    ppLabel818: TppLabel;
    ppLabel819: TppLabel;
    ppShape1525: TppShape;
    ppShape1526: TppShape;
    ppShape1527: TppShape;
    ppShape1528: TppShape;
    ppShape1529: TppShape;
    ppShape1530: TppShape;
    ppShape1531: TppShape;
    ppLabel820: TppLabel;
    ppLabel821: TppLabel;
    Memo1: TMemo;
    ppShape461: TppShape;
    ppLabel109: TppLabel;
    ppLabel162: TppLabel;
    ppLabel163: TppLabel;
    ppShape463: TppShape;
    ppLabel178: TppLabel;
    ppShape467: TppShape;
    ppShape468: TppShape;
    ppShape469: TppShape;
    ppShape472: TppShape;
    ppShape473: TppShape;
    ppShape482: TppShape;
    ppShape485: TppShape;
    ppShape494: TppShape;
    ppShape495: TppShape;
    ppShape504: TppShape;
    ppShape505: TppShape;
    ppShape514: TppShape;
    ppShape515: TppShape;
    ppLabel179: TppLabel;
    ppShape443: TppShape;
    ppShape444: TppShape;
    ppLabel35: TppLabel;
    ppShape445: TppShape;
    ppShape446: TppShape;
    ppShape448: TppShape;
    ppShape450: TppShape;
    ppShape451: TppShape;
    ppShape452: TppShape;
    ppShape474: TppShape;
    ppShape475: TppShape;
    ppShape476: TppShape;
    ppShape486: TppShape;
    ppShape487: TppShape;
    ppShape488: TppShape;
    ppShape496: TppShape;
    ppLabel145: TppLabel;
    ppShape518: TppShape;
    ppShape524: TppShape;
    ppShape525: TppShape;
    ppShape526: TppShape;
    ppLabel146: TppLabel;
    ppLabel149: TppLabel;
    ppLabel150: TppLabel;
    ppShape527: TppShape;
    ppShape528: TppShape;
    ppShape534: TppShape;
    ppLabel151: TppLabel;
    ppLabel152: TppLabel;
    ppLabel165: TppLabel;
    ppShape535: TppShape;
    ppLabel166: TppLabel;
    ppLabel184: TppLabel;
    ppLabel185: TppLabel;
    ppLabel188: TppLabel;
    ppShape536: TppShape;
    ppShape537: TppShape;
    ppLabel189: TppLabel;
    ppShape538: TppShape;
    ppLabel192: TppLabel;
    ppShape544: TppShape;
    ppShape1214: TppShape;
    ppLabel193: TppLabel;
    ppShape1215: TppShape;
    ppLabel196: TppLabel;
    ppShape1216: TppShape;
    ppShape1217: TppShape;
    ppLabel197: TppLabel;
    ppShape1218: TppShape;
    ppShape1219: TppShape;
    ppShape1220: TppShape;
    ppLabel200: TppLabel;
    ppShape1221: TppShape;
    ppShape1222: TppShape;
    ppLabel201: TppLabel;
    ppShape1223: TppShape;
    ppShape1224: TppShape;
    ppShape1225: TppShape;
    ppLabel204: TppLabel;
    ppShape1226: TppShape;
    ppShape1227: TppShape;
    ppLabel205: TppLabel;
    ppShape1228: TppShape;
    ppShape1229: TppShape;
    ppShape1230: TppShape;
    ppLabel208: TppLabel;
    ppShape1231: TppShape;
    ppShape1232: TppShape;
    ppLabel209: TppLabel;
    ppShape1233: TppShape;
    ppShape1234: TppShape;
    ppShape1235: TppShape;
    ppLabel212: TppLabel;
    ppShape1236: TppShape;
    ppShape1237: TppShape;
    ppLabel213: TppLabel;
    ppShape1238: TppShape;
    ppShape1239: TppShape;
    ppShape1240: TppShape;
    ppLabel216: TppLabel;
    ppShape1241: TppShape;
    ppShape1242: TppShape;
    ppLabel217: TppLabel;
    ppShape1243: TppShape;
    ppShape1244: TppShape;
    ppShape1245: TppShape;
    ppLabel220: TppLabel;
    ppShape1246: TppShape;
    ppShape1247: TppShape;
    ppLabel221: TppLabel;
    ppShape1248: TppShape;
    ppShape1249: TppShape;
    ppShape1250: TppShape;
    ppLabel224: TppLabel;
    ppShape1251: TppShape;
    ppShape1252: TppShape;
    ppLabel225: TppLabel;
    ppShape1253: TppShape;
    ppShape1254: TppShape;
    ppShape1255: TppShape;
    ppLabel228: TppLabel;
    ppShape1256: TppShape;
    ppShape1257: TppShape;
    ppLabel229: TppLabel;
    ppShape1258: TppShape;
    ppShape1259: TppShape;
    ppShape1260: TppShape;
    ppLabel465: TppLabel;
    ppShape1261: TppShape;
    ppShape1262: TppShape;
    ppLabel466: TppLabel;
    ppShape1263: TppShape;
    ppShape1264: TppShape;
    ppShape1265: TppShape;
    ppLabel478: TppLabel;
    ppShape1266: TppShape;
    ppShape1267: TppShape;
    ppLabel680: TppLabel;
    ppShape1268: TppShape;
    ppShape1269: TppShape;
    ppShape1270: TppShape;
    ppLabel681: TppLabel;
    ppShape1271: TppShape;
    ppShape1272: TppShape;
    ppLabel682: TppLabel;
    ppShape1273: TppShape;
    ppShape1274: TppShape;
    ppShape1275: TppShape;
    ppLabel683: TppLabel;
    ppLabel684: TppLabel;
    ppLabel685: TppLabel;
    ppShape1276: TppShape;
    ppLabel686: TppLabel;
    ppShape1277: TppShape;
    ppShape1278: TppShape;
    ppShape1279: TppShape;
    ppShape1280: TppShape;
    ppShape1281: TppShape;
    ppShape1282: TppShape;
    ppShape1283: TppShape;
    ppShape1304: TppShape;
    ppShape1305: TppShape;
    ppShape1306: TppShape;
    ppShape1307: TppShape;
    ppShape1308: TppShape;
    ppShape1309: TppShape;
    ppShape1314: TppShape;
    ppShape1315: TppShape;
    ppLabel687: TppLabel;
    ppShape1316: TppShape;
    ppShape1317: TppShape;
    ppShape1318: TppShape;
    ppShape1319: TppShape;
    ppShape1679: TppShape;
    ppShape1680: TppShape;
    ppShape1681: TppShape;
    ppShape1682: TppShape;
    ppShape1688: TppShape;
    ppShape1689: TppShape;
    ppShape1690: TppShape;
    ppShape1691: TppShape;
    ppShape1692: TppShape;
    ppLabel688: TppLabel;
    ppImage8: TppImage;
    ppLine24: TppLine;
    ppLabel112: TppLabel;
    ppShape279: TppShape;
    ppLabel114: TppLabel;
    ppShape285: TppShape;
    ppShape286: TppShape;
    ppLabel115: TppLabel;
    ppShape287: TppShape;
    ppLabel116: TppLabel;
    ppShape288: TppShape;
    ppLabel117: TppLabel;
    ppShape289: TppShape;
    ppLabel118: TppLabel;
    ppShape290: TppShape;
    ppLabel119: TppLabel;
    ppShape291: TppShape;
    ppLabel120: TppLabel;
    ppShape292: TppShape;
    ppLabel121: TppLabel;
    ppShape293: TppShape;
    ppLabel122: TppLabel;
    ppShape294: TppShape;
    ppLabel123: TppLabel;
    ppShape284: TppShape;
    ppLabel124: TppLabel;
    ppShape295: TppShape;
    ppLabel125: TppLabel;
    ppShape296: TppShape;
    ppLine55: TppLine;
    ppLabel126: TppLabel;
    ppLine56: TppLine;
    ppLabel127: TppLabel;
    ppShape297: TppShape;
    ppShape298: TppShape;
    ppLabel128: TppLabel;
    ppLine57: TppLine;
    ppShape283: TppShape;
    ppShape299: TppShape;
    ppLabel110: TppLabel;
    ppLabel129: TppLabel;
    ppShape300: TppShape;
    ppShape301: TppShape;
    ppLabel130: TppLabel;
    ppShape302: TppShape;
    ppLabel131: TppLabel;
    ppShape303: TppShape;
    ppLabel132: TppLabel;
    ppShape304: TppShape;
    ppLabel133: TppLabel;
    ppShape305: TppShape;
    ppLabel134: TppLabel;
    ppShape306: TppShape;
    ppLabel135: TppLabel;
    ppShape307: TppShape;
    ppLabel136: TppLabel;
    ppShape308: TppShape;
    ppLabel137: TppLabel;
    ppShape309: TppShape;
    ppLabel138: TppLabel;
    ppShape310: TppShape;
    ppLabel139: TppLabel;
    ppShape311: TppShape;
    ppLabel140: TppLabel;
    ppShape312: TppShape;
    ppLine58: TppLine;
    ppLabel141: TppLabel;
    ppLine59: TppLine;
    ppLabel143: TppLabel;
    ppShape313: TppShape;
    ppShape314: TppShape;
    ppLabel144: TppLabel;
    ppLine60: TppLine;
    ppShape315: TppShape;
    ppShape316: TppShape;
    ppLabel258: TppLabel;
    ppLabel259: TppLabel;
    ppShape317: TppShape;
    ppShape318: TppShape;
    ppLabel260: TppLabel;
    ppShape319: TppShape;
    ppLabel261: TppLabel;
    ppShape320: TppShape;
    ppLabel262: TppLabel;
    ppShape321: TppShape;
    ppLabel263: TppLabel;
    ppShape322: TppShape;
    ppLabel264: TppLabel;
    ppShape323: TppShape;
    ppLabel265: TppLabel;
    ppShape324: TppShape;
    ppLabel266: TppLabel;
    ppShape325: TppShape;
    ppLabel267: TppLabel;
    ppShape326: TppShape;
    ppLabel268: TppLabel;
    ppShape327: TppShape;
    ppLabel269: TppLabel;
    ppShape328: TppShape;
    ppLabel270: TppLabel;
    ppShape329: TppShape;
    ppLine61: TppLine;
    ppLabel271: TppLabel;
    ppLine62: TppLine;
    ppLabel272: TppLabel;
    ppShape330: TppShape;
    ppShape331: TppShape;
    ppLabel273: TppLabel;
    ppLine63: TppLine;
    ppShape332: TppShape;
    ppShape333: TppShape;
    ppLabel274: TppLabel;
    ppLabel275: TppLabel;
    ppShape334: TppShape;
    ppShape335: TppShape;
    ppLabel276: TppLabel;
    ppShape336: TppShape;
    ppLabel277: TppLabel;
    ppShape337: TppShape;
    ppLabel278: TppLabel;
    ppShape338: TppShape;
    ppLabel279: TppLabel;
    ppShape339: TppShape;
    ppLabel280: TppLabel;
    ppShape340: TppShape;
    ppLabel281: TppLabel;
    ppShape341: TppShape;
    ppLabel282: TppLabel;
    ppShape342: TppShape;
    ppLabel283: TppLabel;
    ppShape343: TppShape;
    ppLabel284: TppLabel;
    ppShape344: TppShape;
    ppLabel285: TppLabel;
    ppShape345: TppShape;
    ppLabel286: TppLabel;
    ppShape346: TppShape;
    ppLine64: TppLine;
    ppLabel287: TppLabel;
    ppLine65: TppLine;
    ppLabel288: TppLabel;
    ppShape347: TppShape;
    ppShape348: TppShape;
    ppLabel289: TppLabel;
    ppLine66: TppLine;
    ppShape349: TppShape;
    ppShape350: TppShape;
    ppLabel290: TppLabel;
    ppLabel291: TppLabel;
    ppShape351: TppShape;
    ppShape352: TppShape;
    ppLabel292: TppLabel;
    ppShape353: TppShape;
    ppLabel293: TppLabel;
    ppShape354: TppShape;
    ppLabel294: TppLabel;
    ppShape355: TppShape;
    ppLabel295: TppLabel;
    ppShape356: TppShape;
    ppLabel296: TppLabel;
    ppShape357: TppShape;
    ppLabel297: TppLabel;
    ppShape358: TppShape;
    ppLabel298: TppLabel;
    ppShape359: TppShape;
    ppLabel299: TppLabel;
    ppShape360: TppShape;
    ppLabel300: TppLabel;
    ppShape361: TppShape;
    ppLabel301: TppLabel;
    ppShape362: TppShape;
    ppLabel302: TppLabel;
    ppShape363: TppShape;
    ppLine67: TppLine;
    ppLabel303: TppLabel;
    ppLine68: TppLine;
    ppLabel304: TppLabel;
    ppShape364: TppShape;
    ppShape365: TppShape;
    ppLabel305: TppLabel;
    ppLine69: TppLine;
    ppShape366: TppShape;
    ppShape367: TppShape;
    ppLabel306: TppLabel;
    ppLabel307: TppLabel;
    ppShape368: TppShape;
    ppShape369: TppShape;
    ppLabel308: TppLabel;
    ppShape370: TppShape;
    ppLabel309: TppLabel;
    ppShape371: TppShape;
    ppLabel310: TppLabel;
    ppShape372: TppShape;
    ppLabel311: TppLabel;
    ppShape373: TppShape;
    ppLabel312: TppLabel;
    ppShape374: TppShape;
    ppLabel313: TppLabel;
    ppShape375: TppShape;
    ppLabel314: TppLabel;
    ppShape376: TppShape;
    ppLabel315: TppLabel;
    ppShape377: TppShape;
    ppLabel316: TppLabel;
    ppShape378: TppShape;
    ppLabel317: TppLabel;
    ppShape379: TppShape;
    ppLabel318: TppLabel;
    ppShape380: TppShape;
    ppLine70: TppLine;
    ppLabel319: TppLabel;
    ppLine71: TppLine;
    ppLabel320: TppLabel;
    ppShape381: TppShape;
    ppShape382: TppShape;
    ppLabel321: TppLabel;
    ppLine72: TppLine;
    ppShape383: TppShape;
    ppShape384: TppShape;
    ppLabel322: TppLabel;
    ppShape385: TppShape;
    ppLabel323: TppLabel;
    ppShape386: TppShape;
    ppShape387: TppShape;
    ppShape388: TppShape;
    ppShape389: TppShape;
    ppShape390: TppShape;
    ppShape391: TppShape;
    ppShape392: TppShape;
    ppShape393: TppShape;
    ppShape394: TppShape;
    ppLabel324: TppLabel;
    ppLabel325: TppLabel;
    ppLabel326: TppLabel;
    ppLabel327: TppLabel;
    ppLabel328: TppLabel;
    ppLabel329: TppLabel;
    ppLabel330: TppLabel;
    ppLabel331: TppLabel;
    ppLabel332: TppLabel;
    ppLabel333: TppLabel;
    ppShape395: TppShape;
    ppShape396: TppShape;
    ppLine73: TppLine;
    ppLabel334: TppLabel;
    ppLine74: TppLine;
    ppLabel335: TppLabel;
    ppShape397: TppShape;
    ppLabel336: TppLabel;
    ppLine75: TppLine;
    ppShape398: TppShape;
    ppShape400: TppShape;
    ppShape401: TppShape;
    ppLabel337: TppLabel;
    ppShape402: TppShape;
    ppShape403: TppShape;
    ppShape404: TppShape;
    ppShape405: TppShape;
    ppShape406: TppShape;
    ppShape407: TppShape;
    ppShape408: TppShape;
    ppShape409: TppShape;
    ppShape410: TppShape;
    ppLabel338: TppLabel;
    ppLabel339: TppLabel;
    ppLabel340: TppLabel;
    ppLabel341: TppLabel;
    ppLabel342: TppLabel;
    ppLabel343: TppLabel;
    ppLabel344: TppLabel;
    ppLabel345: TppLabel;
    ppLabel346: TppLabel;
    ppShape411: TppShape;
    ppLabel347: TppLabel;
    ppLabel348: TppLabel;
    ppLabel349: TppLabel;
    ppLabel350: TppLabel;
    ppLabel351: TppLabel;
    ppLabel352: TppLabel;
    ppLabel360: TppLabel;
    ppDBText29: TppDBText;
    Query_ImpressaoPersonalizacaoOPDadosCarrinho: TStringField;
    Query_ImpressaoPersonalizacaoOPSetor: TStringField;
    Query_ImpressaoPersonalizacaoOPOrdemProducao: TStringField;
    Query_ImpressaoPersonalizacaoOPSequencia: TStringField;
    Query_ImpressaoPersonalizacaoOPStatus: TStringField;
    Query_ImpressaoPersonalizacaoOPEmissao: TDateTimeField;
    Query_ImpressaoPersonalizacaoOPDataPCP: TDateTimeField;
    Query_ImpressaoPersonalizacaoOPDataEncerramento: TDateTimeField;
    Query_ImpressaoPersonalizacaoOPTipo: TStringField;
    Query_ImpressaoPersonalizacaoOPTipoProduto: TStringField;
    Query_ImpressaoPersonalizacaoOPProduto_ID: TStringField;
    Query_ImpressaoPersonalizacaoOPProduto: TStringField;
    Query_ImpressaoPersonalizacaoOPClasseC: TStringField;
    Query_ImpressaoPersonalizacaoOPClasseD: TStringField;
    Query_ImpressaoPersonalizacaoOPArte_ID: TStringField;
    Query_ImpressaoPersonalizacaoOPArte: TStringField;
    Query_ImpressaoPersonalizacaoOPStatusArte: TStringField;
    Query_ImpressaoPersonalizacaoOPPersonalizacao: TStringField;
    Query_ImpressaoPersonalizacaoOPPalleteComBalde: TStringField;
    Query_ImpressaoPersonalizacaoOPTamparia_ID: TStringField;
    Query_ImpressaoPersonalizacaoOPTamparia: TStringField;
    Query_ImpressaoPersonalizacaoOPRoteiro: TStringField;
    Query_ImpressaoPersonalizacaoOPInjetora_FK: TStringField;
    Query_ImpressaoPersonalizacaoOPInjetora: TStringField;
    Query_ImpressaoPersonalizacaoOPFerramenta: TStringField;
    Query_ImpressaoPersonalizacaoOPItem: TStringField;
    Query_ImpressaoPersonalizacaoOPQuantidade: TFloatField;
    Query_ImpressaoPersonalizacaoOPProduzida: TFloatField;
    Query_ImpressaoPersonalizacaoOPSaldo: TFloatField;
    Query_ImpressaoPersonalizacaoOPCentroCusto: TStringField;
    Query_ImpressaoPersonalizacaoOPPedido: TStringField;
    Query_ImpressaoPersonalizacaoOPQtdPorEmbalagem: TIntegerField;
    Query_ImpressaoPersonalizacaoOPGrupo: TStringField;
    Query_ImpressaoPersonalizacaoOPPeso: TStringField;
    Query_ImpressaoPersonalizacaoOPVolumeNominal: TStringField;
    Query_ImpressaoPersonalizacaoOPGrupoEmp: TStringField;
    Query_ImpressaoPersonalizacaoOPEmpenhado_ID: TStringField;
    Query_ImpressaoPersonalizacaoOPProdutoEmp: TStringField;
    Query_ImpressaoPersonalizacaoOPArmazemEmp: TStringField;
    Query_ImpressaoPersonalizacaoOPUndEmp: TStringField;
    Query_ImpressaoPersonalizacaoOPEmpenhado: TFloatField;
    CDS_ImpressaoPersonalizacaoOPDadosCarrinho: TStringField;
    CDS_ImpressaoPersonalizacaoOPSetor: TStringField;
    CDS_ImpressaoPersonalizacaoOPOrdemProducao: TStringField;
    CDS_ImpressaoPersonalizacaoOPSequencia: TStringField;
    CDS_ImpressaoPersonalizacaoOPStatus: TStringField;
    CDS_ImpressaoPersonalizacaoOPEmissao: TDateTimeField;
    CDS_ImpressaoPersonalizacaoOPDataPCP: TDateTimeField;
    CDS_ImpressaoPersonalizacaoOPDataEncerramento: TDateTimeField;
    CDS_ImpressaoPersonalizacaoOPTipo: TStringField;
    CDS_ImpressaoPersonalizacaoOPTipoProduto: TStringField;
    CDS_ImpressaoPersonalizacaoOPProduto_ID: TStringField;
    CDS_ImpressaoPersonalizacaoOPProduto: TStringField;
    CDS_ImpressaoPersonalizacaoOPClasseC: TStringField;
    CDS_ImpressaoPersonalizacaoOPClasseD: TStringField;
    CDS_ImpressaoPersonalizacaoOPArte_ID: TStringField;
    CDS_ImpressaoPersonalizacaoOPArte: TStringField;
    CDS_ImpressaoPersonalizacaoOPStatusArte: TStringField;
    CDS_ImpressaoPersonalizacaoOPPersonalizacao: TStringField;
    CDS_ImpressaoPersonalizacaoOPPalleteComBalde: TStringField;
    CDS_ImpressaoPersonalizacaoOPTamparia_ID: TStringField;
    CDS_ImpressaoPersonalizacaoOPTamparia: TStringField;
    CDS_ImpressaoPersonalizacaoOPRoteiro: TStringField;
    CDS_ImpressaoPersonalizacaoOPInjetora_FK: TStringField;
    CDS_ImpressaoPersonalizacaoOPInjetora: TStringField;
    CDS_ImpressaoPersonalizacaoOPFerramenta: TStringField;
    CDS_ImpressaoPersonalizacaoOPItem: TStringField;
    CDS_ImpressaoPersonalizacaoOPQuantidade: TFloatField;
    CDS_ImpressaoPersonalizacaoOPProduzida: TFloatField;
    CDS_ImpressaoPersonalizacaoOPSaldo: TFloatField;
    CDS_ImpressaoPersonalizacaoOPCentroCusto: TStringField;
    CDS_ImpressaoPersonalizacaoOPPedido: TStringField;
    CDS_ImpressaoPersonalizacaoOPQtdPorEmbalagem: TIntegerField;
    CDS_ImpressaoPersonalizacaoOPGrupo: TStringField;
    CDS_ImpressaoPersonalizacaoOPPeso: TStringField;
    CDS_ImpressaoPersonalizacaoOPVolumeNominal: TStringField;
    CDS_ImpressaoPersonalizacaoOPGrupoEmp: TStringField;
    CDS_ImpressaoPersonalizacaoOPEmpenhado_ID: TStringField;
    CDS_ImpressaoPersonalizacaoOPProdutoEmp: TStringField;
    CDS_ImpressaoPersonalizacaoOPArmazemEmp: TStringField;
    CDS_ImpressaoPersonalizacaoOPUndEmp: TStringField;
    CDS_ImpressaoPersonalizacaoOPEmpenhado: TFloatField;

    procedure ImprimirOrdemBomixPersonalizacao(VLC_Ordem : String; VLN_Recno: Integer);


  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  OrdemProducao_ImprimirOP_Arquivos: TOrdemProducao_ImprimirOP_Arquivos;

implementation

{$R *.dfm}

uses FuncaoSistema_Unit, OrdemProducaoImprimirOP_Unit, ConexaoDados_Unit;

procedure TOrdemProducao_ImprimirOP_Arquivos.ImprimirOrdemBomixPersonalizacao(VLC_Ordem : String; VLN_Recno: Integer);
Var
   VLC_Select : String;

begin

       VLC_Select := '  Select Distinct ' + #13;
       VLC_Select := VLC_Select + '  ' + #13;
       VLC_Select := VLC_Select + '   DadosCarrinho, Setor, OrdemProducao, Sequencia, Status, Emissao, DataPCP, DataEncerramento, Tipo, TB.TipoProduto, ' + #13;
       VLC_Select := VLC_Select + '   TB.Produto_ID, TB.Produto, TB.ClasseC, TB.ClasseD, TB.Arte_ID, TB.Arte, TB.StatusArte, TB.Personalizacao, ' + #13;
       VLC_Select := VLC_Select + '   Case When ((Produto.PalleteComBalde = ' + '''' + 'Sim' + '''' +  ') Or (TB.PalleteComBalde = ' + '''' + 'Sim' + '''' + ')) ' + #13;
       VLC_Select := VLC_Select + '   then ' + '''' + 'OBS: PALETIZAÇÃO UNIFICADA: BALDE + TAMPA' + '''' + ' else ' + '''' + '' + '''' + ' end PalleteComBalde, ' + #13;
       VLC_Select := VLC_Select + '   Produto.Produto_ID as Tamparia_ID,  Produto.Produto + ' + '''' + ' <---> SALDO (E2): ' + '''' + #13;
       VLC_Select := VLC_Select + '   + (Select Top 1 Cast(B2_QATU as Varchar(10)) from P12OFICIAL.dbo.SB2010 (nolock) where B2_LOCAL = ' + '''' + 'E2' + '''' + #13;
       VLC_Select := VLC_Select + '   AND B2_FILIAL = ' + '''' + '010101' + '''' + ' AND B2_COD = Produto.Produto_ID) as Tamparia, Roteiro, Injetora_FK, Injetora, ' + #13;
       VLC_Select := VLC_Select + '   Ferramenta, TB.Item, Quantidade, Produzida, Saldo, TB.CentroCusto, Pedido, ' + #13;
       VLC_Select := VLC_Select + '   QtdPorEmbalagem, TB.Grupo, TB.Peso,	VolumeNominal, GrupoEmp, Empenhado_ID, ProdutoEmp, ' + #13;
       VLC_Select := VLC_Select + '   ArmazemEmp, UndEmp, Empenhado  ' + #13;
       VLC_Select := VLC_Select + ' ' + #13;
       VLC_Select := VLC_Select + '  from ( ' + #13;
       VLC_Select := VLC_Select + ' ' + #13;
       VLC_Select := VLC_Select + '     Select Distinct ' + #13;
       VLC_Select := VLC_Select + '        Cast(Carrinho as Varchar(10)) + ' + '''' + ' / ' + '''' + ' + Cast(QtdCarrinho as Varchar(10)) as DadosCarrinho, ' + #13;
       VLC_Select := VLC_Select + '        Item.Mix, Case When Substring(Item.Produto,1,1) = ' + '''' + 'B' + '''' + ' then ' + #13;
       VLC_Select := VLC_Select + '        (Select top 1 Produto_ID from BomixBI.dbo.Fat_TB_PedidoVendaItem  Tampa Where Item.Mix = Tampa.Mix ' + #13;
       VLC_Select := VLC_Select + '        AND Tampa.Pedido_FK = Item.Pedido_FK AND Tampa.C6_Empresa = Item.C6_Empresa AND TipoProduto = ' + '''' + 'TAMPA' + '''' +  ')' + #13;
       VLC_Select := VLC_Select + '        else ' + #13;
       VLC_Select := VLC_Select + '        (Select top 1 Produto_ID from BomixBI.dbo.Fat_TB_PedidoVendaItem  Balde Where Item.Mix = Balde.Mix' + #13;
       VLC_Select := VLC_Select + '        AND Balde.Pedido_FK = OrdemProducao.Pedido AND Balde.C6_Empresa = OrdemProducao.Empresa AND Balde.TipoProduto = ' + '''' + 'BALDE' + '''' +  ')' + #13;
       VLC_Select := VLC_Select + '        end as Tamparia_ID, OrdemProducao.*, Empenhado.Grupo as GrupoEmp,' + #13;
       VLC_Select := VLC_Select + '        Empenhado.Produto_ID as Empenhado_ID, Empenhado.Produto as ProdutoEmp,' + #13;
       VLC_Select := VLC_Select + '        Empenhado.Unidade as UndEmp, Empenhado, Empenhado.Armazem as ArmazemEmp' + #13;
       VLC_Select := VLC_Select + ' ' + #13;
       VLC_Select := VLC_Select + '   from BomixBI.dbo.Pcp_TB_OrdemProducao (Nolock) OrdemProducao' + #13;
       VLC_Select := VLC_Select + '   Left Join BomixBI.dbo.Fat_TB_PedidoVendaItem Item  (nolock) ON Item.Pedido_FK = OrdemProducao.Pedido' + #13;
       VLC_Select := VLC_Select + '   AND Item.Sequencia = OrdemProducao.Sequencia AND Item.C6_Empresa = OrdemProducao.Empresa' + #13;
       VLC_Select := VLC_Select + '   Inner Join BomixBI.dbo.Pcp_TB_ProdutoEmpenho (nolock) Empenhado ON Empenhado.C2_Recno = OrdemProducao.Recno' + #13;
       VLC_Select := VLC_Select + ' Where OrdemProducao.Setor in (' + '''' + 'PERSONALIZACAO' + '''' + ',' + '''' + 'PALETIZACAO PE' + '''' + ')' + #13;

       if OrdemProducao_ImprimirOP.GetRecursoPrioridade(VLC_Ordem) = 'Sim' then
             VLC_Select :=  VLC_Select + ' AND Prioridade < 500' + #13;

       VLC_Select := VLC_Select + ' AND OrdemProducao.OrdemProducao = ' + '''' + VLC_Ordem + '''' + #13;
       VLC_Select := VLC_Select + '                  ) TB' + #13;
       VLC_Select := VLC_Select + '                  Left Join BomixBI.dbo.Pcp_TB_Produto (nolock) Produto ON Produto.Produto_ID = Tamparia_ID' + #13;


       CDS_ImpressaoPersonalizacaoOP.Close;
       Query_ImpressaoPersonalizacaoOP.Close;
       Query_ImpressaoPersonalizacaoOP.SQL.Clear;
       Query_ImpressaoPersonalizacaoOP.SQL.Text := VLC_Select;
       CDS_ImpressaoPersonalizacaoOP.Open;


       if (Copy(CDS_ImpressaoPersonalizacaoOPProduto_ID.AsString,1,4) = 'P02D')
       then
       begin

             ppLabel719.Caption := 'Data Impressão: ' + DateTimeToStr(Date());
             ppLabel720.Caption := Sys_FuncaoSistema.PNL_UsuarioAtivo.Caption;

             if CDS_ImpressaoPersonalizacaoOPPersonalizacao.AsString <> '' then
             begin
                  ppLabel710.Visible := True;
                  ppDBText73.Visible := True;
                  ppLabel709.Visible := True;
                  ppDBText74.Visible := True;
                  ppDBText75.Visible := True;
             end
             else
             begin
                  ppLabel710.Visible := False;
                  ppDBText73.Visible := False;
                  ppLabel709.Visible := False;
                  ppDBText74.Visible := False;
                  ppDBText75.Visible := False;
             end;

             ppImage3.Picture := Sys_FuncaoSistema.Img_LogoBomix.Picture;
             ppImprimirPersonalizacaoHTD.Print;

       end
       else
       begin

             ppLBL_UsuarioPersonalizacao.Caption := 'Data Impressão: ' + DateTimeToStr(Date());
             ppLBL_DataPersonalizacao.Caption := Sys_FuncaoSistema.PNL_UsuarioAtivo.Caption;

             if CDS_ImpressaoPersonalizacaoOPPersonalizacao.AsString <> '' then
             begin
                  ppLabel102.Visible := True;
                  ppDBText19.Visible := True;
                  ppLabel101.Visible := True;
                  ppDBText20.Visible := True;
                  ppDBText37.Visible := True;
             end
             else
             begin
                  ppLabel102.Visible := False;
                  ppDBText19.Visible := False;
                  ppLabel101.Visible := False;
                  ppDBText20.Visible := False;
                  ppDBText37.Visible := False;
             end;

             ppImage1.Picture := Sys_FuncaoSistema.Img_LogoBomix.Picture;
             ppImage8.Picture := Sys_FuncaoSistema.Img_LogoBomix.Picture;
             ppImprimirPersonalizacao.Print;
       end;

end;


end.
